export const categories = {
    Pantry: "Pantry: Pickles, Dairy, Condiments and Spice Mixes",
    Breakfast: "Breakfast and Brunch",
    SmallPlates: "Small Plates and Spreads",
    Salads: "Salads",
    Soups: "Soups",
    WeekdayDinners: "Weekday Dinners",
    SpecialOccasions: "Sharing and Special Occasions",
    Bread: "Bread",
    Sweets: "Sweets",
}

export const recipes = {
    "QUICK MAKDOUS (PRESERVED EGGPLANT IN OLIVE OIL)": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 18,
        "recipe": "Quick makdous (preserved eggplant in olive oil)",
        "translation": "Makdous Bitinjan",
        "yield": "Serves 6–8 as part of a spread",
        "ingredients": [
            "4 quarts / 4 liters water",
            "1 tbsp granulated sugar",
            "½ lemon",
            "2 eggplants, stems trimmed and cut into 1-inch / 3cm chunks (1½ lbs / 700g)",
            "1 cup / 100g walnuts, roughly chopped",
            "2 green chiles, finely chopped (1 oz / 30g)",
            "3 garlic cloves, crushed to a paste",
            "1 tbsp red pepper paste (page 29)",
            "1 tbsp shatta (page 26)",
            "1¼ cups / 300ml olive oil",
            "salt"
        ]
    },
    "EASY PICKLED BABY EGGPLANT": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 21,
        "recipe": "Easy pickled baby eggplant",
        "translation": "Makbus Bitinjan",
        "yield": "Serves 10 as a side or part of a spread",
        "ingredients": [
            "1½ tbsp coarse sea salt",
            "3 tbsp granulated sugar",
            "1 cup / 230ml white vinegar",
            "2 cups / 500ml water",
            "10 baby eggplants (1 lb 5 oz / 600g)",
            "2 tbsp coriander seeds",
            "3 garlic cloves, halved",
            "1 green chile, cut into 3 pieces",
            "olive oil",
            "chopped fresh cilantro"
        ]
    },
    "PICKLED FRESH ZA’ATAR, CHILE & LEMON": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 22,
        "recipe": "Pickled fresh za’atar, chile & lemon",
        "translation": "Makbus Za’atar w Laymonn",
        "yield": "Makes a medium jar",
        "ingredients": [
            "1½ cups / 30g fresh za’atar or oregano leaves",
            "1 lemon (4 oz / 120g)",
            "2 large green chiles, thinly sliced (¾ oz / 25g)",
            "salt",
            "¾ cup / 180ml olive oil"
        ]
    },
    "LABNEH": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 23,
        "recipe": "Labneh",
        "translation": "Labneh",
        "yield": "Makes 20 balls, about 500g",
        "ingredients": [
            "1 quart / 1kg Greek yogurt",
            "salt",
            "olive oil"
        ]
    },
    "BURNT CHILE SALSA": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 24,
        "recipe": "Burnt chile salsa",
        "translation": "Shatta Mishwiyyeh",
        "yield": "Makes a small jar",
        "ingredients": [
            "5 large red chiles (3¾ oz / 110g)",
            "5 garlic cloves, unpeeled (1 oz / 27g)",
            "5 tbsp / 75ml olive oil, plus more for sealing",
            "1 tsp apple cider vinegar",
            "heaping ¼ tsp ground cumin",
            "½ tsp Urfa chile flakes (optional)",
            "salt"
        ]
    },
    "SHATTA (RED OR GREEN CHILESAUCE)": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 26,
        "recipe": "Shatta (red or green chilesauce)",
        "translation": "Shatta Hamrah w Khadra",
        "yield": "Makes a medium jar",
        "ingredients": [
            "11 oz / 300g long red or green chiles, stems removed, thinly sliced (with seeds)",
            "salt",
            "2 tbsp apple cider vinegar",
            "2 tbsp lemon juice",
            "3–4 tbsp olive oil, enough to cover and seal"
        ]
    },
    "GREEN LEMON SAUCE": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 28,
        "recipe": "Green lemon sauce",
        "translation": "Tatbeelet Laymonn Khadra",
        "yield": "Makes a small jar",
        "ingredients": [
            "½ cup / 10g fresh parsley, finely chopped",
            "1 green chile, finely chopped",
            "5 tbsp / 75ml lemon juice",
            "2 tbsp white wine vinegar",
            "2 garlic cloves, crushed to a paste",
            "salt"
        ]
    },
    "RED PEPPER PASTE": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 29,
        "recipe": "Red pepper paste",
        "translation": "Dips al Filfil",
        "yield": "Makes a small jar",
        "ingredients": [
            "4–5 large red peppers (2 lb 2 oz / 1kg)",
            "2 tbsp olive oil, plus more for sealing",
            "6 large red chiles, trimmed and roughly chopped (4¼ oz / 120g)",
            "1½ tsp sweet paprika",
            "1½ tsp ground cumin",
            "2 tbsp apple cider vinegar",
            "salt"
        ]
    },
    "TAHINI SAUCE": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 32,
        "recipe": "Tahini sauce",
        "translation": "Tahinia",
        "yield": "Makes a small jar",
        "ingredients": [
            "Rounded ½ cup / 150g tahini paste",
            "½ cup / 120ml cold water",
            "3 tbsp lemon juice",
            "1 small garlic clove, crushed to a paste",
            "salt"
        ]
    },
    "SUMAC ONIONS": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 33,
        "recipe": "Sumac onions",
        "translation": "Basal bil Sumac",
        "yield": "Makes a medium-size jar",
        "ingredients": [
            "1 large red onion, cut in half, then each half thinly sliced",
            "1½ tbsp sumac",
            "7 tbsp / 100ml apple cider vinegar",
            "7 tbsp / 100ml water",
            "3 tbsp lemon juice",
            "salt"
        ]
    },
    "TOASTED NUTS & SEEDS": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 35,
        "recipe": "Toasted nuts & seeds",
        "translation": "Khaltet Mukassarat",
        "yield": "Makes a medium jar",
        "ingredients": [
            "½ cup / 50g blanched almonds",
            "⅓ cup / 50g pine nuts",
            "heaping ⅓ cup / 50g pumpkin seeds",
            "⅓ cup / 50g sunflower seeds",
            "2 tbsp olive oil",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "salt",
            "1 tbsp sumac"
        ]
    },
    "GAZAN DUKKAH": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 36,
        "recipe": "Gazan dukkah",
        "translation": "Duqqa Ghazawiya",
        "yield": "Makes a small jar",
        "ingredients": [
            "¼ cup / 50g cracked wheat or bulgur wheat",
            "1 tsp cumin seeds",
            "1 tsp coriander seeds",
            "1 tsp caraway seeds",
            "1 tsp dill seeds",
            "3 tbsp sesame seeds",
            "1 tbsp sumac",
            "heaping ¼ tsp Aleppo chile flakes (or regular chile flakes)",
            "salt"
        ]
    },
    "SWEET BAHARAT": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 38,
        "recipe": "Sweet baharat",
        "translation": "Baharat el Ka’ak",
        "yield": "Makes a small jar",
        "ingredients": [
            "7 tsp / 15g fennel seeds",
            "4½ tsp / 8g anise seeds",
            "2 tsp mastic",
            "5½ tsp / 12g mahlab"
        ]
    },
    "BAHARAT": {
        "chapter_idx": 1,
        "category": "Pantry: pickles, dairy, condiments and spice mixes",
        "page": 39,
        "recipe": "Baharat",
        "translation": "Baharat",
        "yield": "Makes a small jar",
        "ingredients": [
            "1 tsp black peppercorns",
            "1 tsp coriander seeds",
            "5–6 cardamom pods",
            "⅓ of a whole nutmeg, grated",
            "1 small cinnamon stick, roughly chopped",
            "½ tsp whole cloves",
            "1½ tsp cumin seeds",
            "1½ tsp whole allspice berries"
        ]
    },
    "BRAISED EGGS WITH PITA BREAD, TOMATOES & ZA’ATAR": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 45,
        "recipe": "Braised eggs with pita bread, tomatoes & za’atar",
        "translation": "Beyd Makli ma’ Khobez w Za’atar",
        "yield": "Serves 4",
        "ingredients": [
            "2 pita breads (7 oz / 200g)",
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "4 green onions, thinly sliced (3½ oz / 100g)",
            "2 medium tomatoes, roughly chopped (10 oz / 285g)",
            "1 green chile, seeded and finely chopped (¾ oz / 20g)",
            "salt and black pepper",
            "4 eggs",
            "2 tsp za’atar"
        ]
    },
    "GAZAN FAVA BEAN FALAFEL": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 46,
        "recipe": "Gazan fava bean falafel",
        "translation": "Falafel Ghazawi",
        "yield": "Makes 20 pieces, to serve 4–6",
        "ingredients": [
            "9 oz / 250g dried split fava beans",
            "1 medium leek, thinly sliced, including most of the green part (3½ oz / 100g)",
            "1 garlic clove, crushed to a paste",
            "1 cup / 20g fresh parsley, roughly chopped",
            "1 cup / 20g fresh cilantro, roughly chopped",
            "1 tsp ground cumin",
            "½ tsp baking powder",
            "salt",
            "1 tbsp white sesame seeds",
            "1 tbsp coriander seeds, coarsely crushed",
            "sunflower oil, for frying (about 2 cups / 500ml)",
            "tahini, tomato & mint dip (page 92)",
            "bread",
            "pickles"
        ]
    },
    "CRUSHED LENTILS WITH TAHINI & SOFT-BOILED EGGS": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 50,
        "recipe": "Crushed lentils with tahini & soft-boiled eggs",
        "translation": "Adas Medames",
        "yield": "Serves 2 as a main, 4 as part of a spread",
        "ingredients": [
            "2 large eggs (optional)",
            "¼ cup / 60 ml olive oil, plus more to finish",
            "3 garlic cloves, peeled and crushed to a paste",
            "1 green chile, finely chopped",
            "1 tsp ground cumin",
            "1 x 14-oz / 400g can of beluga/brown lentils, drained and rinsed (12 oz / 330g)",
            "3 medium tomatoes, peeled and cut into ½-inch / 1cm dice (10½ oz / 300g)",
            "1 cup / 20g fresh cilantro leaves, roughly chopped, plus more whole leaves for serving",
            "¼ cup / 60g tahini paste",
            "3 tbsp lemon juice",
            "5 tbsp / 70ml water",
            "salt and black pepper",
            "sumac onions (page 33)",
            "pan-fried turmeric bread (page 241) or pita"
        ]
    },
    "EGGPLANT & FAVA BEANS WITH EGGS": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 53,
        "recipe": "Eggplant & fava beans with eggs",
        "translation": "Bitinjan w Ful ma’ Beyd",
        "yield": "Serves 4",
        "ingredients": [
            "2 medium eggplants (around 1 lb 6 oz / 630g)",
            "⅓ cup / 80ml olive oil, plus more to serve",
            "salt and black pepper",
            "1 onion, finely chopped (1¼ cups / 175g)",
            "6 garlic cloves, crushed to a paste",
            "1 small piece of ginger, peeled and finely grated (¾ oz / 20g)",
            "1 green chile, finely chopped, seeds and all (¾ oz / 20g)",
            "1 tsp chile flakes",
            "1 tsp ground cumin",
            "½ tsp ground cinnamon",
            "1½ tsp tomato paste",
            "2 plum tomatoes, chopped into ¾-inch / 2cm chunks (10½ oz / 300g)",
            "1 x 14-oz / 400g can of diced tomatoes",
            "1 x 14-oz / 400g can of fava beans, drained",
            "1¼ cups / 300ml water",
            "¾ cup / 15g fresh cilantro, roughly chopped, plus more to serve",
            "4 large eggs",
            "¼ cup / 30g sumac onions (page 33)"
        ]
    },
    "CARDAMOM PANCAKES WITH TAHINI, HALVA & CAROB": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 54,
        "recipe": "Cardamom pancakes with tahini, halva & carob",
        "translation": "Fatayer ma’ kharroub w Halaweh",
        "yield": "Makes 12 pancakes, to serve 4",
        "ingredients": [
            "2 large eggs",
            "2 tbsp granulated sugar",
            "7 tbsp / 100ml heavy cream",
            "½ cup plus 2 tbsp / 150ml whole milk",
            "2¼ cups / 9½ oz / 270g all-purpose flour",
            "¾ tsp ground cardamom",
            "½ tsp anise seeds",
            "heaping ¼ tsp ground turmeric",
            "2 tsp baking powder",
            "salt",
            "3 tbsp sunflower oil, plus more for frying",
            "1 tbsp nigella seeds",
            "3 tbsp / 50g tahini paste",
            "2½ tbsp / 50g carob molasses",
            "¼ cup / 60g plain halva, broken into large chunks",
            "flaked sea salt"
        ]
    },
    "ZUCCHINI & LEEK IJEH (ARABIC FRITTATA)": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 58,
        "recipe": "Zucchini & leek ijeh (Arabic frittata)",
        "translation": "Ijehet Kousa w Kurrath",
        "yield": "Serves 4–6",
        "ingredients": [
            "1⅔ cups / 250g frozen peas, thawed",
            "2 zucchini (10½ oz / 300g)",
            "1 small onion (5¼ oz / 150g)",
            "1 large leek, finely chopped (6 oz / 175g)",
            "⅓ cup plus 1 tbsp / 1¾ oz / 50g all-purpose flour",
            "¾ cup / 15g fresh parsley, finely chopped",
            "½ cup / 10g fresh mint leaves, thinly shredded",
            "1¼ tsp dried mint",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "½ tsp ground turmeric",
            "1 tsp dill or fennel seeds, slightly crushed",
            "3 large eggs, lightly beaten",
            "salt and black pepper",
            "3 tbsp olive oil",
            "lemon wedges",
            "sour cream"
        ]
    },
    "SCRAMBLED EGG & BURNT CHILE CHERRY TOMATO TOAST": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 60,
        "recipe": "Scrambled egg & burnt chile cherry tomato toast",
        "translation": "Beyd bil Shatta w al Banadoura ‘ala Toast",
        "yield": "Serves 4",
        "ingredients": [
            "3 tbsp olive oil",
            "14 oz / 400g cherry tomatoes",
            "4 garlic cloves, thinly sliced",
            "salt and black pepper",
            "1 tbsp rose harissa",
            "4 sourdough slices, about ½-inch / 1cm thick",
            "2 tbsp / 35g butter, at room temperature",
            "8 eggs",
            "¼ cup / 60ml heavy cream",
            "¼ cup / 50g sour cream",
            "2 tbsp fresh chives, finely sliced",
            "2 tbsp fresh oregano leaves",
            "burnt chile salsa (page 24)"
        ]
    },
    "HERBY CRUSHED PEA & AVOCADO TOAST": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 63,
        "recipe": "Herby crushed pea & avocado toast",
        "translation": "Bazilla w Avokado ‘ala Toast",
        "yield": "Serves 4",
        "ingredients": [
            "2 cups / 300g frozen peas, thawed",
            "4 green onions, finely sliced",
            "¼ cup / 5g fresh cilantro leaves, roughly chopped",
            "¼ cup / 5g fresh mint leaves, roughly chopped",
            "3 tbsp / 45ml olive oil, plus more for drizzling",
            "salt and black pepper",
            "2 small ripe avocados, peeled and cut into 1¼-inch / 3cm chunks (about 7 oz / 200g)",
            "4 sourdough slices, about ½-inch / 1cm thick",
            "burnt chile salsa (page 24)",
            "lime wedges"
        ]
    },
    "FETA, SHAVED CUCUMBER & DUKKAH TOAST": {
        "chapter_idx": 2,
        "category": "Breakfast and brunch",
        "page": 64,
        "recipe": "Feta, shaved cucumber & dukkah toast",
        "translation": "Jibnet Feta w Khiyar ‘ala Toast",
        "yield": "Serves 4",
        "ingredients": [
            "4 Persian or 2 regular cucumbers (9¾ oz / 280g)",
            "flaked sea salt",
            "7 oz / 200g feta cheese",
            "⅔ cup / 130g Greek yogurt",
            "1 tsp nigella seeds",
            "½ tsp lemon zest",
            "1 small garlic clove, crushed to a paste",
            "salt",
            "1 tbsp lemon juice",
            "1½ tsp fennel seeds, finely crushed",
            "olive oil",
            "4 sourdough slices, about ½-inch / 1cm thick",
            "1 tbsp Gazan dukkah (page 36)",
            "1½ tsp sumac",
            "20 fresh mint leaves"
        ]
    },
    "GREEN KISHK (FERMENTED YOGURT & BULGUR)": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 72,
        "recipe": "Green kishk (fermented yogurt & bulgur)",
        "translation": "Kishk Akhdar",
        "yield": "Serves 4–6 as part of a spread",
        "ingredients": [
            "½ cup / 100g coarse whole-grain bulgur",
            "2 cups / 500g Greek yogurt",
            "salt",
            "1½ tbsp / 25g labneh (page 23)",
            "1 tsp dried mint",
            "1 tsp dill seeds, coarsely crushed",
            "1 tsp dried oregano",
            "1 tsp Aleppo chile flakes (or regular chile flakes), plus more for serving",
            "2–3 green onions, finely sliced (1¾ oz / 50g)",
            "½ cup / 50g walnuts, toasted",
            "olive oil"
        ]
    },
    "CHUNKY EGGPLANT M’TABBAL": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 74,
        "recipe": "Chunky eggplant m’tabbal",
        "translation": "M’tabbal Bitinjan",
        "yield": "Serves 4 as part of a spread",
        "ingredients": [
            "3 medium eggplants (about 1¾ lb / 800g)",
            "1 garlic clove, crushed to a paste",
            "1½ tbsp lemon juice",
            "2 tbsp olive oil, plus more for the pan and drizzling",
            "salt",
            "1 recipe tahini sauce (page 32)",
            "10 small fresh basil leaves",
            "2 tbsp fresh oregano or za’atar leaves"
        ]
    },
    "ROASTED VEGETABLES WITH LEMON &ZA’ATAR": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 76,
        "recipe": "Roasted vegetables with lemon &za’atar",
        "translation": "Khudar bil Laymonn w al Za’atar",
        "yield": "Serves 6 as part of a spread",
        "ingredients": [
            "2 small parsnips, peeled and cut into large chunks (7 oz / 200g)",
            "1 small rutabaga, or 2 large turnips, peeled and cut into large batons (about 1 lb / 450g)",
            "3 large carrots, peeled and cut into thick diagonal slices (12¼ oz / 350g)",
            "2 red bell peppers, cut into thick batons (14 oz / 400g)",
            "3 celery stalks, cut into 1½-inch / 4cm pieces (7 oz / 200g)",
            "2 red onions, peeled and cut into wedges (10½ oz / 300g)",
            "2 heads of garlic, cut in half horizontally",
            "1 small green chile, chopped, optional",
            "1 tbsp red shatta (page 26) or rose harissa",
            "2 tbsp za’atar",
            "¼ cup / 60ml olive oil",
            "1 tbsp capers, rinsed and chopped",
            "¾ cup plus 2 tbsp / 200ml vegetable stock or water",
            "2 tbsp lemon juice",
            "salt and black pepper",
            "rounded ½ cup / 150g tahini",
            "2 tbsp lemon juice",
            "⅔ cup / 160ml cold water",
            "½ cup / 5g fresh parsley, chopped",
            "2 tsp sesame seeds, lightly toasted",
            "1 tsp sumac"
        ]
    },
    "CRUSHED BUTTER BEANS WITH ORANGE, MAKDOUS & MINT": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 79,
        "recipe": "Crushed butter beans with orange, makdous & mint",
        "translation": "Fasoulia beyda ma’ Makdous",
        "yield": "Serves 4",
        "ingredients": [
            "1 orange (7 oz / 200g)",
            "5 tbsp / 75ml olive oil, plus more to finish",
            "4 garlic cloves, crushed to a paste",
            "2 x 14 oz / 400g cans or 1 x 25 oz / 700g jar of butter beans (approx. 18 oz / 500g drained weight), drained and rinsed",
            "2 tbsp lemon juice",
            "3 tbsp / 50ml cold water",
            "salt",
            "2½ oz / 70g makdous (page 18)",
            "¼ cup / 5g fresh mint leaves, roughly torn, plus more to serve"
        ]
    },
    "CHOPPED SALAD FOR EVERY OCCASION": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 80,
        "recipe": "Chopped salad for every occasion",
        "translation": "Salata Mafrumeh",
        "yield": "Serves 4",
        "ingredients": [
            "4 small Persian cucumbers, or 1 large regular cucumber (10½ oz / 300g)",
            "10½ oz / 300g ripe plum tomatoes, cut into ¼-inch / ½cm dice",
            "10–12 radishes, cut into ¼-inch / ½cm dice (4½ oz / 130g)",
            "2 green chiles, seeded and finely chopped",
            "about 5 green onions, finely sliced (2½ oz / 70g)",
            "3 tbsp olive oil, plus more for drizzling",
            "1½ cups / 30g fresh parsley, very finely chopped",
            "1 large garlic clove, crushed to a paste",
            "3 tbsp lemon juice",
            "1 tsp dill seeds, slightly crushed",
            "salt"
        ]
    },
    "GHAZZAWI TAHINI CHOPPED SALAD": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 83,
        "recipe": "Ghazzawi tahini chopped salad",
        "translation": "Salata Ghazawiya",
        "yield": "Serves 4",
        "ingredients": [
            "4 small Persian cucumbers, or 1 large regular cucumber, peeled, quartered lengthwise, seeds removed and cut into ¼-inch / ½cm dice (10½ oz / 300g)",
            "10½ oz / 300g ripe tomatoes (either 2 large or 4 plum tomatoes), cut into ¼-inch / ½cm dice",
            "10–12 radishes, cut into ¼-inch / ½cm dice (5 oz / 140g)",
            "2 green chiles, seeded and finely chopped",
            "about 5 green onions, finely sliced (2½ oz / 70g)",
            "3 tbsp olive oil, plus more for drizzling",
            "1½ cups / 30g fresh parsley, very finely chopped",
            "¾ cup / 15g fresh dill, finely chopped",
            "rounded ¼ cup / 80g tahini paste",
            "1 tbsp sumac",
            "1 large garlic clove, crushed to a paste",
            "3 tbsp lemon juice",
            "1½ tsp toasted dill or fennel seeds",
            "salt"
        ]
    },
    "GREEN BEANS WITH LEEK & TOMATO": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 84,
        "recipe": "Green beans with leek & tomato",
        "translation": "Fasoulia Khadra bil zeit",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "¼ cup / 60ml olive oil",
            "3 leeks, cut into ¼-inch / ½cm slices (10½ oz / 300g)",
            "salt and black pepper",
            "1 carrot, peeled and thinly sliced (2½ oz / 70g)",
            "4 large garlic cloves, thinly sliced",
            "1 large green chile, finely chopped",
            "2 tsp tomato paste",
            "1 lb 2 oz / 500g flat or Romano beans, trimmed and cut into 3-inch / 7–8cm long pieces",
            "3 large tomatoes, cut into ½-inch / 1cm cubes (1 lb / 450g)",
            "7 tbsp / 100ml water",
            "1 tsp ground cumin"
        ]
    },
    "SMOKY CHICKPEAS WITH CILANTRO TAHINI": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 88,
        "recipe": "Smoky chickpeas with cilantro tahini",
        "translation": "Hummus Hab bil Tahinia w al Kuzbara",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "2 x 14-oz / 400g cans of chickpeas, drained and rinsed",
            "4 tbsp olive oil, plus more for drizzling",
            "½ tsp smoked paprika",
            "½ tsp Aleppo chile flakes (or regular dried chile flakes)",
            "½ tsp sweet paprika",
            "¼ tsp ground cinnamon",
            "salt",
            "2 tbsp lemon juice",
            "1 recipe tahini sauce (page 32)",
            "1½ cups / 30g fresh cilantro, chopped, plus a few more leaves to garnish"
        ]
    },
    "TOMATO, ARUGULA & WALNUT SALAD": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 89,
        "recipe": "Tomato, arugula & walnut salad",
        "translation": "Salatet Jarjeer w Banadoura",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "¼ cup / 40g walnuts",
            "¼ cup / 60ml olive oil",
            "3 garlic cloves, crushed to a paste",
            "2½ oz / 70g sun-dried tomatoes in oil, finely chopped",
            "2 tbsp capers, drained, rinsed and patted dry",
            "1¼ cups / 25g arugula",
            "½ cup / 10g fresh parsley",
            "½ cup / 10g fresh cilantro",
            "1 tbsp plus 1 tsp pomegranate molasses",
            "heaping ¼ tsp Aleppo chile flakes (or regular dried chile flakes)",
            "1 tsp lemon zest",
            "salt and black pepper"
        ]
    },
    "TAHINI, TOMATO & MINT DIP": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 92,
        "recipe": "Tahini, tomato & mint dip",
        "translation": "Tahinia ma’ Banadoura w Na’na",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "2 large ripe tomatoes (12 oz / 350g), finely chopped",
            "½ cup / 120g tahini paste",
            "2 large garlic cloves, crushed to a paste",
            "1 tbsp red shatta (page 26)",
            "2 tsp lemon zest",
            "¼ cup / 60ml lemon juice",
            "salt",
            "¼ cup / 5g fresh mint leaves, finely chopped, plus more to garnish",
            "1 tsp dried mint",
            "2 tbsp olive oil"
        ]
    },
    "FERMENTED TURNIP TOPS": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 95,
        "recipe": "Fermented turnip tops",
        "translation": "Huwairna",
        "yield": "Serves 8 as part of a mezze or spread",
        "ingredients": [
            "14 oz / 400g turnip tops, leaves picked and very finely chopped",
            "salt",
            "2 cups / 600g Greek yogurt",
            "shatta (page 26)",
            "2 tbsp olive oil",
            "½ tsp sumac (or heaping ¼ tsp chile flakes)"
        ]
    },
    "BRAISED CHARD WITH CRISPY ONIONS & SUMAC": {
        "chapter_idx": 3,
        "category": "Small plates and spreads",
        "page": 96,
        "recipe": "Braised chard with crispy onions & sumac",
        "translation": "Saleq ma’ Basal",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "1 lb / 450g Swiss chard, leaves pulled off the stems, and leaves and stems chopped into roughly ¾ inch / 2cm pieces",
            "6 tbsp / 90ml sunflower oil",
            "1 medium onion (6 oz / 175g), thinly sliced",
            "1 tbsp cornstarch",
            "3 tbsp olive oil",
            "salt",
            "1 small garlic clove, thinly sliced",
            "½ tsp Aleppo chile flakes (or regular dried chile flakes)",
            "2 tsp sumac",
            "lemon wedges, to serve"
        ]
    },
    "GARLIC-INFUSED BROCCOLI & LABNEH DIP": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 102,
        "recipe": "Garlic-infused broccoli & labneh dip",
        "translation": "Broccoli bil Toum w al Labneh",
        "yield": "Serves 4",
        "ingredients": [
            "¼ cup / 60ml olive oil",
            "3 large garlic cloves, peeled and thinly sliced",
            "9 oz / 250g broccoli florets",
            "1¼ cups / 350g labneh (page 23) or thick Greek yogurt",
            "1 tbsp lemon juice",
            "1 red chile, seeded and finely chopped",
            "½ cup / 10g fresh dill, finely chopped",
            "½ cup / 10g fresh parsley, finely chopped",
            "¼ cup / 5g fresh mint leaves, roughly shredded",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "salt and black pepper",
            "2 tsp sumac"
        ]
    },
    "BEETS WITH CUMIN LABNEH, TOASTED NUTS & SEEDS & CHIVES": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 104,
        "recipe": "Beets with cumin labneh, toasted nuts & seeds & chives",
        "translation": "Salatet Shamander bil Labneh",
        "yield": "Serves 4",
        "ingredients": [
            "2 lbs 2 oz / 1kg beets",
            "⅔ cup / 200g labneh (page 23) or thick Greek yogurt",
            "1 heaping tsp lemon zest",
            "1 tsp ground cumin",
            "salt and black pepper",
            "2 tbsp apple cider vinegar",
            "6 tbsp / 90ml olive oil",
            "2 tbsp toasted nuts and seeds (page 35)",
            "2 tbsp finely chopped fresh chives",
            "1 golden beet (8 oz / 230g)",
            "1 cup / 250ml water",
            "2 tbsp apple cider vinegar",
            "1 tsp granulated sugar",
            "heaping ¼ tsp ground turmeric"
        ]
    },
    "CRUSHED FAVA BEANS WITH GOAT CHEESE & PRESERVED LEMONSALSA": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 108,
        "recipe": "Crushed fava beans with goat cheese & preserved lemonsalsa",
        "translation": "M’tabbal Ful Akhdar",
        "yield": "Serve 4–6 as a side or part of a spread",
        "ingredients": [
            "12¼ oz / 350g frozen fava beans, thawed",
            "1 cup / 150g frozen peas, thawed",
            "2 garlic cloves, crushed to a paste",
            "2 tbsp lemon juice",
            "3 tbsp olive oil",
            "½ cup / 10g fresh mint leaves, thinly shredded, plus a few to garnish",
            "1 green chile, seeded and finely chopped",
            "½ cup / 10g fresh dill, finely chopped",
            "½ cup / 10g fresh parsley, finely chopped",
            "salt and black pepper",
            "4¼ oz / 120g soft goat cheese, crumbled",
            "1 green chile, seeded and finely chopped",
            "1 preserved lemon, flesh removed and finely chopped (about ½ oz / 15g)",
            "2 tbsp sumac",
            "2 tbsp olive oil"
        ]
    },
    "ROASTED EGGPLANT WITH TOMATO, POMEGRANATE & HERBS": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 112,
        "recipe": "Roasted eggplant with tomato, pomegranate & herbs",
        "translation": "Salatet Bitinjan",
        "yield": "Serves 4 as part of a spread",
        "ingredients": [
            "1 lb 5oz / 600g baby or Japanese eggplants",
            "6 tbsp / 90ml olive oil, plus more for drizzling",
            "salt and black pepper",
            "10½ oz / 300g mixed-color cherry tomatoes, halved",
            "2 garlic cloves, crushed to a paste",
            "½ cup / 10g fresh parsley, chopped",
            "¼ cup / 5g fresh mint leaves, finely shredded",
            "2 tbsp lemon juice",
            "2 tbsp pomegranate molasses",
            "10 basil leaves"
        ]
    },
    "WATERMELON, CUCUMBER SALAD WITH FETA & LEMON VERBENA": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 113,
        "recipe": "Watermelon, cucumber salad with feta & lemon verbena",
        "translation": "Salatet Batikh w Khyar ma’ Jibneh",
        "yield": "Serves 4",
        "ingredients": [
            "1 lb 2 oz / 500g watermelon, cut into small slices (about ½ a small melon)",
            "1 cucumber, peeled and cut into chunks (about 6 oz / 180g)",
            "1 small red onion, peeled and very thinly sliced (⅔ cup / 80g)",
            "1 green chile, thinly sliced",
            "1¾ oz / 50g pitted Kalamata olives",
            "1 tbsp runny honey",
            "1 tbsp pomegranate molasses",
            "1 tbsp lemon juice",
            "2 tbsp extra-virgin olive oil",
            "salt",
            "2½ oz / 75g feta cheese or goat cheese, crumbled",
            "10 fresh mint leaves",
            "10 fresh lemon verbena or basil leaves",
            "1 tsp nigella seeds"
        ]
    },
    "FRIDGE-RAID FATTOUSH": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 117,
        "recipe": "Fridge-raid fattoush",
        "translation": "Fattoush",
        "yield": "Serves 4–6",
        "ingredients": [
            "2–3 stale whole-wheat pita breads",
            "12 oz / 350g mixed-color tomatoes",
            "1 large cucumber (10½ oz / 300g)",
            "1 red pepper (5¼ oz / 150g)",
            "1 large garlic clove, crushed to a paste",
            "3 tbsp lemon juice",
            "1½ tbsp white wine vinegar",
            "1½ tbsp pomegranate molasses",
            "¼ cup / 60ml olive oil",
            "½ tsp cumin seeds, toasted and coarsely crushed",
            "¾ tsp coriander seeds, toasted and coarsely crushed",
            "1 tbsp sumac, plus more for sprinkling",
            "salt",
            "4¼ oz / 120g radishes, thinly sliced",
            "1 large banana shallot, thinly sliced (2½ oz / 70g)",
            "3–4 green onions, thinly sliced",
            "1 cup / 20g fresh parsley, roughly chopped",
            "¾ cup / 15g fresh mint, finely shredded",
            "½ cup / 10g fresh cilantro, roughly chopped"
        ]
    },
    "CUCUMBER & FETA YOGURT WITH DILL, ALMONDS & ROSE": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 118,
        "recipe": "Cucumber & feta yogurt with dill, almonds & rose",
        "translation": "Khyar bil Laban",
        "yield": "Serves 6 as a side",
        "ingredients": [
            "4 small Persian cucumbers or 1 large",
            "2 cups / 500g labneh (page 23) or thick Greek yogurt",
            "4¼ oz / 120g feta, crumbled",
            "1 fat garlic clove, crushed to a paste",
            "2 tbsp lemon juice",
            "1 tbsp olive oil, plus more for drizzling",
            "salt",
            "1 tbsp each of fresh cilantro, dill and mint, roughly chopped, plus more mint to garnish",
            "½ tsp dried mint",
            "1 large green chile, seeded and finely chopped",
            "1 lime, peeled, segmented and roughly chopped",
            "¼ cup / 20g almonds, toasted and roughly chopped",
            "2 tbsp dill fronds",
            "½ tsp nigella seeds",
            "1 tsp dried rose petals"
        ]
    },
    "ROASTED ASPARAGUS WITH FETA, ALMONDS & MINT": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 121,
        "recipe": "Roasted asparagus with feta, almonds & mint",
        "translation": "Halyoun",
        "yield": "Serves 4",
        "ingredients": [
            "¼ cup / 25g sliced almonds",
            "2 tsp nigella seeds, slightly crushed",
            "2 tsp lemon zest",
            "1½ tbsp lemon juice",
            "2 tbsp olive oil",
            "1 small garlic clove, crushed to a paste",
            "heaping ¼ tsp granulated sugar",
            "salt and black pepper",
            "20 thick asparagus spears (10½ oz / 300g)",
            "1 tbsp olive oil",
            "2¼ oz / 60g feta cheese, crumbled",
            "10 small fresh mint leaves",
            "½ tsp Aleppo chile flakes (or regular chile flakes)"
        ]
    },
    "BITTER LEAVES, FENNEL & ORANGE SALAD": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 122,
        "recipe": "Bitter leaves, fennel & orange salad",
        "translation": "Salatet Shumar w Burtuqal",
        "yield": "Serves 4–6 as a starter or side",
        "ingredients": [
            "4 blood oranges or regular oranges",
            "¼ cup / 60ml lemon juice",
            "2 tbsp orange juice",
            "5 tbsp / 75ml olive oil",
            "1 tbsp pomegranate molasses",
            "2 tsp orange blossom water",
            "salt and black pepper",
            "3½ oz / 100g radicchio leaves",
            "3½ oz / 100g white or red endive (1 small endive)",
            "½ small red onion",
            "1 small fennel bulb",
            "6 cups / 120g arugula",
            "¼ cup / 5g fresh mint leaves, roughly torn",
            "¼ cup / 5g fresh tarragon leaves",
            "2½ oz / 70g hard goat cheese, broken into chunks",
            "3 tbsp pomegranate seeds",
            "3 tbsp / 25g sunflower seeds, toasted"
        ]
    },
    "TURMERIC CAULIFLOWER & CHICKPEAS WITH LEMON YOGURT": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 126,
        "recipe": "Turmeric cauliflower & chickpeas with lemon yogurt",
        "translation": "Zahra ma’ Hummus",
        "yield": "Serves 4 as a side",
        "ingredients": [
            "1 small cauliflower, cut into 1¼-inch / 3cm florets (keeping some of the tender leaves) (1¾ lbs / 800g)",
            "1 x 14-oz / 400g can of chickpeas, drained and rinsed",
            "4 garlic cloves, peeled but left whole",
            "3 tbsp olive oil",
            "1½ tsp ground turmeric",
            "¾ tsp smoked paprika",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "salt",
            "⅔ cup / 200g thick yogurt or labneh (page 23)",
            "1 tsp lemon zest",
            "1 tbsp lemon juice",
            "¼ cup / 5g fresh mint leaves, roughly chopped",
            "¼ cup / 5g fresh cilantro leaves, roughly chopped",
            "lemon wedges, to serve"
        ]
    },
    "FRIED EGGPLANT M’TABBAL WITH TOMATO & CILANTRO SALSA": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 127,
        "recipe": "Fried eggplant m’tabbal with tomato & cilantro salsa",
        "translation": "M’tabbal Bitinjan Makli",
        "yield": "Serves 4",
        "ingredients": [
            "3 medium eggplants (1 lb 14 oz / 850g)",
            "salt and black pepper",
            "¼ cup / 60g tahini paste",
            "½ cup / 150g Greek yogurt",
            "¼ cup / 60ml lemon juice",
            "2 large garlic cloves, crushed to a paste",
            "2 cups / 500ml sunflower oil",
            "2 large plum tomatoes, coarsely grated (8 oz / 230g)",
            "3 tbsp olive oil",
            "½ cup / 10g fresh cilantro, roughly chopped"
        ]
    },
    "FENNEL, KOHLRABI & CILANTRO SALAD": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 131,
        "recipe": "Fennel, kohlrabi & cilantro salad",
        "translation": "Salatet Shumar w Kohlrabi",
        "yield": "Serves 2–4",
        "ingredients": [
            "2 medium kohlrabi (6 oz / 180g)",
            "1 large fennel bulb (7 oz / 200g)",
            "salt and black pepper",
            "¾ cup plus 2 tbsp / 250g Greek yogurt",
            "1 green chile, seeded and finely chopped",
            "1 garlic clove, crushed to a paste",
            "1 tbsp orange zest",
            "2 tbsp lemon juice",
            "1 tbsp olive oil, plus more for drizzling",
            "¾ cup / 15g fresh cilantro, roughly chopped",
            "½ cup / 10g fresh mint leaves, thinly shredded",
            "1 tsp dried mint"
        ]
    },
    "TOMATO, ZA’ATAR & SUMACSALAD": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 132,
        "recipe": "Tomato, za’atar & sumacsalad",
        "translation": "Salatet Za’atar w Banadoura bil Sumac",
        "yield": "Serves 4",
        "ingredients": [
            "3 large ripe tomatoes, cut into ¼-inch / ½cm wedges (14 oz / 400g)",
            "14 oz / 400g cherry tomatoes, cut in half",
            "½ red onion, finely chopped (½ cup / 70g)",
            "¾ cup / 15g fresh parsley, finely chopped",
            "1 tbsp sumac, plus more for sprinkling",
            "3 tbsp olive oil",
            "½ tsp lemon zest",
            "2½ tbsp lemon juice",
            "1 tbsp pomegranate molasses",
            "salt",
            "¾ cup / 15g fresh za’atar or oregano leaves, roughly chopped",
            "3 tbsp pomegranate seeds"
        ]
    },
    "ROASTED CAULIFLOWER WITH TAHINI & CRUSHED TOMATOES": {
        "chapter_idx": 4,
        "category": "Salads",
        "page": 135,
        "recipe": "Roasted cauliflower with tahini & crushed tomatoes",
        "translation": "Salatet Zahra bil Tahinia",
        "yield": "Serves 4 as a side or part of a spread",
        "ingredients": [
            "2 large tomatoes (9 oz / 260g)",
            "salt",
            "1 tbsp apple cider vinegar",
            "3 tbsp olive oil, plus more for drizzling",
            "1 large cauliflower, cut into 1¼–1½-inch / 3–4cm florets (about 2 lbs 2 oz / 1kg)",
            "1 green chile, thinly sliced",
            "½ tsp ground cinnamon",
            "heaping ¼ tsp ground allspice",
            "½ tsp ground turmeric",
            "salt and black pepper",
            "rounded ½ cup / 150g tahini sauce (page 32)",
            "2 tbsp / 3g fresh parsley, roughly chopped"
        ]
    },
    "CHILLED TOMATO & AVOCADO SOUP WITH BURNT CHILE": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 140,
        "recipe": "Chilled tomato & avocado soup with burnt chile",
        "translation": "Shorbet Banadoura w Avokado",
        "yield": "Serves 4–6",
        "ingredients": [
            "1 lb 2 oz / 500g ripe plum tomatoes, cored, peeled and roughly chopped",
            "4½ oz / 130g red bell pepper, seeded and roughly chopped",
            "4½ oz / 130g celery, roughly chopped",
            "3 garlic cloves, roughly chopped",
            "2 tbsp olive oil",
            "1½ tbsp apple cider vinegar",
            "1 cup / 200ml tomato passata",
            "1 tsp sweet paprika",
            "salt",
            "½ a medium ripe avocado (3 oz / 80g), peeled and pitted",
            "2 pita breads",
            "1 tbsp olive oil",
            "1 oz / 30g cucumber, chopped",
            "½ a medium ripe avocado (3 oz / 80g), peeled, pitted and chopped",
            "1 oz / 30g red bell pepper, chopped",
            "¼ cup / 5g fresh mint leaves",
            "burnt chile salsa (page 24)"
        ]
    },
    "RED LENTIL, DRIED MINT & LEMON SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 142,
        "recipe": "Red lentil, dried mint & lemon soup",
        "translation": "Shorbet Adas bil Laymonn",
        "yield": "Serves 4–6",
        "ingredients": [
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "1 medium onion, finely chopped (1¼ cups / 185g)",
            "1 medium potato, peeled and cut into ½-inch / 1cm cubes (6⅓ oz / 180g)",
            "1 large carrot, peeled and cut into ½-inch / 1cm cubes (6 oz / 170g)",
            "2 celery stalks, cut into ¼-inch / ½cm cubes (3 oz / 90g)",
            "1¼ cups / 250g split red lentils, rinsed and drained",
            "5 cups / 1.2 liters hot vegetable stock",
            "heaping ¼ tsp ground turmeric",
            "2 tsp ground cumin",
            "salt and black pepper",
            "2 tsp dried mint, plus more for serving",
            "1 tsp Aleppo chile flakes (or regular chile flakes), plus more for serving",
            "2 lemons, peeled and cut into ¼-inch / ½cm dice",
            "¼ cup / 5g fresh cilantro leaves",
            "1 tsp cumin seeds, toasted and slightly crushed"
        ]
    },
    "JERUSALEMITE-ARMENIAN YOGURT SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 144,
        "recipe": "Jerusalemite-Armenian yogurt soup",
        "translation": "Shorbet Laban Armaniya—Qudsiyy",
        "yield": "Serves 4",
        "ingredients": [
            "3½ oz / 100g maftoul (pearl couscous), rinsed and drained",
            "salt and black pepper",
            "¼ cup / 60ml olive oil",
            "1 onion, finely chopped (¾ cup / 130g)",
            "1½ cups / 400g Greek yogurt",
            "7 tbsp / 100ml heavy cream",
            "1¼ cups / 300ml vegetable stock",
            "1 large egg, lightly whisked",
            "1 tbsp cornstarch",
            "¼ cup / 5g fresh parsley, finely chopped",
            "2 garlic cloves, thinly sliced",
            "5 radishes, cut into thin matchsticks",
            "2 tbsp finely shredded fresh mint"
        ]
    },
    "CHILLED TABBOULEH SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 147,
        "recipe": "Chilled tabbouleh soup",
        "translation": "Shorbet Tabbouleh",
        "yield": "Serves 4",
        "ingredients": [
            "⅔ cup / 120g fine bulgur wheat",
            "1¼ cups / 300ml boiling water",
            "1 lb 2 oz / 500g tomatoes, peeled and roughly chopped",
            "1 garlic clove, crushed to a paste",
            "½ cup / 10g fresh parsley, roughly chopped",
            "¼ cup / 5g fresh mint leaves, roughly chopped",
            "3 tbsp red pepper paste (page 29)",
            "1 small onion, peeled and roughly chopped (½ cup / 80g)",
            "1 tbsp lemon juice",
            "¼ cup / 60ml olive oil, plus more for finishing",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "⅛ tsp ground allspice",
            "⅛ tsp ground cinnamon",
            "salt",
            "1 oz / 30g cucumber, chopped into ¼-inch / ½cm dice",
            "1 oz / 30g red bell pepper, chopped into ¼-inch / ½cm dice",
            "¼ cup / 5g fresh parsley, finely chopped",
            "¼ cup / 5g fresh mint, finely shredded"
        ]
    },
    "SWEETCORN, BEAN & GREEN CABBAGE SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 148,
        "recipe": "Sweetcorn, bean & green cabbage soup",
        "translation": "Shorbet Dhurah w Malfoof",
        "yield": "Serves 4",
        "ingredients": [
            "3 tbsp olive oil",
            "1 large onion, finely chopped (1¼ cups / 180g)",
            "2 tbsp tomato paste",
            "1 tbsp red pepper paste (page 29)",
            "1¾ cups / 320g sweetcorn kernels, from about 2 large cobs (frozen sweetcorn can also be used)",
            "1 tsp paprika",
            "1½ tsp ground cumin",
            "salt and black pepper",
            "5¼ oz / 150g green cabbage leaves, chopped into small pieces",
            "1 quart / 1 liter vegetable stock",
            "1 x 14-oz / 400g can of borlotti or any other white beans, drained and rinsed",
            "2 tbsp chopped fresh parsley",
            "lemon wedges",
            "crusty bread"
        ]
    },
    "SWISS CHARD & MAFTOUL SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 150,
        "recipe": "Swiss chard & maftoul soup",
        "translation": "Shorbet Saleq w Maftoul",
        "yield": "Serves 4–6",
        "ingredients": [
            "7 oz / 200g maftoul (pearl couscous)",
            "6⅓ cups / 1.5 liters water",
            "2 tbsp olive oil",
            "1 large onion, chopped",
            "1 bunch of Swiss chard (about 10 leaves), chopped, including ribs (7 oz / 200g)",
            "heaping ¼ tsp baharat (page 39)",
            "salt and black pepper",
            "3 tbsp tomato paste",
            "3 tbsp lemon juice",
            "1 x 14-oz / 400g can of chickpeas, drained and rinsed",
            "1 tbsp tahini paste (optional)"
        ]
    },
    "BULGUR WHEAT DUMPLING & LENTILSOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 152,
        "recipe": "Bulgur wheat dumpling & lentilsoup",
        "translation": "Kubbet al Raheb",
        "yield": "Serves 4",
        "ingredients": [
            "½ cup / 100g fine brown bulgur wheat",
            "about 2 cups / 500ml cold water",
            "¼ cup / ¾ oz / 25g all-purpose flour",
            "½ small onion, very finely chopped (¼ cup / 35g)",
            "¼ cup / 5g fresh mint leaves, finely shredded",
            "1 tbsp chopped fresh basil",
            "heaping ¼ tsp ground allspice",
            "½ tsp sweet paprika",
            "heaping ¼ tsp Aleppo chile flakes (or regular chile flakes)",
            "salt and black pepper",
            "½ cup / 100g green or brown lentils, rinsed and drained",
            "2 tbsp olive oil",
            "1 medium onion, finely chopped (1¼ cups / 180g)",
            "3 garlic cloves, crushed to a paste",
            "3½ cups / 900ml vegetable stock",
            "5 oz / 140g Swiss chard leaves, finely chopped",
            "2 tbsp lemon juice",
            "2 tbsp chopped fresh parsley"
        ]
    },
    "LEMONY SPINACH SOUP WITH ZA’ATARBREADCRUMBS": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 156,
        "recipe": "Lemony spinach soup with za’atarbreadcrumbs",
        "translation": "Shorbet Sabanikh bil Laymonn",
        "yield": "Serves 6–8",
        "ingredients": [
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "2 leeks, white and light green parts, roughly chopped (12 oz / 350g)",
            "2 celery stalks, roughly chopped (3 oz / 90g)",
            "3 garlic cloves, crushed to a paste",
            "2 sprigs of fresh oregano",
            "2 bay leaves",
            "2 large potatoes, peeled and cut into ¾-inch / 2cm chunks (10½ oz / 300g)",
            "5½ cups / 1.3 liters vegetable stock",
            "salt and black pepper",
            "1 lb / 450g frozen chopped spinach, thawed",
            "1 cup / 20g fresh cilantro, roughly chopped",
            "¾ cup / 15g fresh parsley, roughly chopped",
            "2 tbsp lemon juice",
            "2 tbsp olive oil",
            "½ cup / 50g panko breadcrumbs (try with fried quinoa, see note)",
            "2 tbsp za’atar",
            "heaping ¼ tsp Aleppo chile flakes (or regular chile flakes)",
            "lemon wedges"
        ]
    },
    "FREEKEH & VEGETABLE SOUP": {
        "chapter_idx": 5,
        "category": "Soups",
        "page": 158,
        "recipe": "Freekeh & vegetable soup",
        "translation": "Shorbet Freekeh ma’ al Khudar",
        "yield": "Serves 6",
        "ingredients": [
            "¾ cup / 150g cracked freekeh",
            "3 tablespoons olive oil, plus more for drizzling",
            "1 large onion, finely chopped 1 cup / 150g",
            "2–3 large celery stalks, cut into ¼-inch / ½cm cubes (7 oz / 200g)",
            "2 medium carrots, peeled and cut into ¼-inch / ½cm cubes (1½ cups / 200g)",
            "3 garlic cloves, crushed to a paste",
            "1½ cups / 1 liter vegetable stock",
            "2 medium zucchini, cut into ½cm cubes (14 oz / 400g)",
            "2 tsp chopped fresh za’atar or oregano leaves",
            "salt and black pepper",
            "heaping ¼ tsp Aleppo chile flakes (or regular chile flakes)",
            "chopped fresh herbs (parsley, chives, green onions or more za’atar)"
        ]
    },
    "FRIED HALLOUMI WITH PURSLANESALAD": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 164,
        "recipe": "Fried halloumi with purslanesalad",
        "translation": "Halloum Maklyeh ma’ Salatet Baqleh",
        "yield": "Serves 4",
        "ingredients": [
            "2 x 8 oz / 225g packets of halloumi (plain)",
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "1 tbsp apple cider vinegar",
            "1½ tbsp runny honey",
            "salt and black pepper",
            "10½ oz / 300g cherry plum tomatoes, cut in half",
            "10½ oz / 300g cucumber, large seeds removed",
            "3 oz / 80g purslane, mâche or mixed leaves",
            "¼ cup / 5g fresh mint leaves",
            "½ cup / 10g fresh basil leaves",
            "¼ cup / 5g fresh oregano leaves",
            "heaping ¼ tsp Aleppo chile flakes (or regular chile flakes)",
            "1½ tsp za’atar",
            "½ cup / 60g sumac onions (page 33)"
        ]
    },
    "ARTICHOKE & POTATO IN OLIVE OIL & PRESERVED LEMON": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 168,
        "recipe": "Artichoke & potato in olive oil & preserved lemon",
        "translation": "Yakhni Ardi Shauki wa Batata",
        "yield": "Serves 4",
        "ingredients": [
            "2 lemons",
            "10 baby violet or 4 large globe artichokes (2½ lbs / 1.2kg)",
            "6–7 medium baby potatoes, cut into quarters (1 lb 5 oz / 600g)",
            "10 large garlic cloves, peeled and cut into quarters, lengthwise",
            "3 sprigs of fresh oregano",
            "5 sprigs of fresh thyme",
            "3 sprigs of fresh parsley",
            "1 green chile, cut into 4 pieces",
            "6 cups / 1½ liters water",
            "3 tbsp apple cider vinegar",
            "salt and black pepper",
            "½ cup plus 2 tbsp / 150ml olive oil",
            "2 tbsp preserved lemon, finely chopped",
            "3 tbsp / 20g capers, roughly chopped",
            "¼ cup / 5g fresh parsley, finely chopped",
            "1 tbsp olive oil"
        ]
    },
    "TWO-LENTIL MEJADRA": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 169,
        "recipe": "Two-lentil mejadra",
        "translation": "Mejadara",
        "yield": "Serves 6",
        "ingredients": [
            "1 cup / 200g Egyptian or short-grain rice",
            "¾ cup / 150g green lentils, rinsed and drained",
            "½ cup / 100g red lentils, rinsed and drained",
            "2 tsp cumin seeds",
            "1½ tbsp coriander seeds",
            "2 tbsp olive oil",
            "2 tsp tomato paste",
            "½ tsp ground turmeric",
            "1½ tsp ground allspice",
            "1½ tsp ground cinnamon",
            "1½ cups / 375ml cold water",
            "2–3 large onions (1 lb 3 oz / 530g)",
            "2 tbsp olive oil",
            "salt and black pepper",
            "⅓ cup / 7g fresh parsley, finely chopped",
            "¼ cup / 5g fresh mint, finely shredded",
            "4 green onions, finely sliced (1¾ oz / 50g)",
            "2 tsp sumac",
            "2 tsp lemon juice",
            "3 tbsp / 3g fresh parsley leaves",
            "1 tsp sumac",
            "Greek yogurt"
        ]
    },
    "CARROTS IN TAMARIND &MINT": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 172,
        "recipe": "Carrots in tamarind &mint",
        "translation": "Jazar bil Tamer Hindi",
        "yield": "Serves 4",
        "ingredients": [
            "2⅓ oz / 65g solid tamarind paste",
            "7 tbsp / 100ml boiling water",
            "2 lbs 2 oz / 1kg carrots (medium size), peeled and cut in half lengthwise",
            "¼ cup / 60ml olive oil",
            "6 garlic cloves, crushed to a paste",
            "1 tsp dried mint",
            "10 cardamom pods, lightly crushed",
            "½ tsp ground cinnamon",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "1½ tsp coriander seeds, lightly crushed",
            "½ tsp granulated sugar",
            "salt and black pepper",
            "¾ cup plus 2 tbsp / 200ml boiling water",
            "¼ cup / 5g fresh mint leaves",
            "¼ cup / 5g fresh cilantro leaves"
        ]
    },
    "FAVA BEANS WITH LEMON & CILANTRO": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 175,
        "recipe": "Fava beans with lemon & cilantro",
        "translation": "Ful Akhdar",
        "yield": "Serves 4 as a main or 6 as a side",
        "ingredients": [
            "2 large lemons",
            "⅓ cup / 80ml olive oil",
            "1 onion, finely chopped (1 cup / 150g)",
            "salt and black pepper",
            "1 lb 5 oz / 600g fresh fava beans, trimmed and cut into 1¼-inch / 3cm pieces",
            "6 garlic cloves, crushed to a paste",
            "2 cups / 500ml vegetable stock",
            "1½ cups / 30g fresh cilantro, roughly chopped"
        ]
    },
    "PALESTINIAN EGG & CHIPS": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 178,
        "recipe": "Palestinian egg & chips",
        "translation": "Batata w Beyd",
        "yield": "Serves 4",
        "ingredients": [
            "4 large potatoes (2½ lbs / 1.2kg)",
            "¼ cup / 60ml plus 1 tsp sunflower oil",
            "2 tbsp / 30g butter",
            "salt and black pepper",
            "2 medium onions, finely chopped (2 cups / 300g)",
            "8 medium eggs",
            "1½ tsp sumac",
            "2 tbsp fresh parsley, roughly chopped",
            "2 tbsp fresh oregano leaves",
            "olive oil"
        ]
    },
    "EGGPLANT & CHICKPEAS WITH GREEN LEMON SAUCE": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 179,
        "recipe": "Eggplant & chickpeas with green lemon sauce",
        "translation": "Bitinjan ma’ Hummus",
        "yield": "Serves 4–6",
        "ingredients": [
            "2 medium eggplants, cut into 1¼-inch / 3cm chunks (1 lb 5 oz / 600g)",
            "6 tbsp / 90ml olive oil",
            "salt and black pepper",
            "1 large onion, finely chopped (1⅔ cups / 240g)",
            "2 celery stalks, cut into ½-inch / 1cm dice (5½ oz / 160g)",
            "1 red pepper, cut into ½-inch / 1cm dice (6 oz / 180g)",
            "8 garlic cloves, crushed to a paste",
            "2 tsp ground cumin",
            "1 tsp ground coriander",
            "½ tsp ground cinnamon",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "1 tsp paprika",
            "½ tsp ground allspice",
            "½ tsp ground turmeric",
            "2 x 14-oz / 400g cans of diced tomatoes",
            "2 x 14-oz / 400g cans of chickpeas, drained and rinsed",
            "1¼ cups / 300ml water",
            "1 recipe green lemon sauce (page 28; replace half the parsley with cilantro)"
        ]
    },
    "LOADED SWEET POTATOES WITH BLACK-EYEDPEAS": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 182,
        "recipe": "Loaded sweet potatoes with black-eyedpeas",
        "translation": "Batata Helweh ma’ Loubia",
        "yield": "Serves 4",
        "ingredients": [
            "2½ lbs / 1.2kg sweet potatoes (about 4 medium)",
            "2 garlic cloves, crushed to a paste",
            "2 tbsp olive oil",
            "heaping ¼ tsp ground cumin",
            "⅛ tsp ground cinnamon",
            "1 x 14-oz / 400g tin of black-eyed peas, drained and rinsed",
            "7 tbsp / 100ml water",
            "salt and black pepper",
            "3½ oz / 100g cherry tomatoes, roughly chopped",
            "1½ tbsp olive oil",
            "2 tbsp / 2½g fresh parsley, finely chopped, plus more leaves to garnish",
            "2 tbsp / 2½g fresh mint leaves, finely sliced, plus more leaves to garnish",
            "1 tbsp lemon juice",
            "flaked sea salt",
            "tahini sauce (page 32)",
            "green lemon sauce (page 28)",
            "olive oil"
        ]
    },
    "CELERIAC & TOMATO BAKE": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 185,
        "recipe": "Celeriac & tomato bake",
        "translation": "Karfs w Banadoura bil Furn",
        "yield": "Serves 4",
        "ingredients": [
            "2 medium celeriac, peeled and cut into 2 x 1¼-inch / 5 x 3½cm chunks (2 lbs 2 oz / 1kg)",
            "5 tbsp / 75ml olive oil",
            "salt and black pepper",
            "2 large red onions, thinly sliced (heaping 2 cups / 260g)",
            "4 garlic cloves, crushed to a paste",
            "1¼ tsp ground cinnamon",
            "½ tsp ground allspice",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "1 tsp coriander seeds",
            "1 tsp cumin seeds",
            "1½ tbsp sumac",
            "1 x 14-oz / 400g can of diced tomatoes",
            "2 eggs",
            "2–3 green onions, thinly sliced (1 oz / 30g)",
            "4¼ oz / 120g hard goat cheese, coarsely grated"
        ]
    },
    "RICE & LENTILS WET PILAF": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 186,
        "recipe": "Rice & lentils wet pilaf",
        "translation": "Sha’aktoura",
        "yield": "Serves 4–6",
        "ingredients": [
            "1 quart / 1 liter water",
            "salt and black pepper",
            "¾ cup plus 2 tbsp / 175g Egyptian or other short-grain rice",
            "¾ cup / 160g split red lentils",
            "3 tbsp olive oil",
            "1 onion, finely chopped (¾ cup / 20g)",
            "5 garlic cloves, crushed to a paste",
            "1 green chile, finely chopped",
            "1 oz / 30g fresh ginger, finely grated",
            "1½ tsp cumin seeds, toasted and finely crushed",
            "1½ tsp coriander seeds, toasted and finely crushed",
            "¾ tsp ground cinnamon",
            "½ tsp ground turmeric",
            "2 tbsp tomato paste",
            "1¼ cups / 300ml water",
            "1 lb 2 oz / 500g frozen spinach, thawed",
            "1¼ cups / 25g fresh cilantro, roughly chopped",
            "1 cup / 20g fresh mint, roughly chopped, plus some whole leaves to serve",
            "3 tbsp lemon juice"
        ]
    },
    "POINTY CABBAGE & TAHINI BIL SINIYHE": {
        "chapter_idx": 6,
        "category": "Weekday dinners",
        "page": 191,
        "recipe": "Pointy cabbage & tahini bil siniyhe",
        "translation": "Malfoof bil Siniyeh",
        "yield": "Serves 4",
        "ingredients": [
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "2 pointy (or hispi/conehead) cabbages, or 1 large white cabbage, cut into quarters, leaving the core intact (1¾ lb / 800g)",
            "salt and black pepper",
            "2 red onions, peeled and thinly sliced (scant 2 cups / 220g)",
            "8 large garlic cloves, peeled and left whole",
            "¼ cup / 60ml apple cider vinegar",
            "1¼ cups / 300ml vegetable stock",
            "4 sprigs fresh oregano or za’atar",
            "½ recipe of tahini sauce (page 32)",
            "2 tbsp chopped fresh parsley",
            "½ tsp Aleppo chile flakes (or regular chile flakes)"
        ]
    },
    "FREEKEH-STUFFED PEPPERS": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 196,
        "recipe": "Freekeh-stuffed peppers",
        "translation": "Mahshi Filfil bil Freekeh",
        "yield": "Serves 8–10",
        "ingredients": [
            "½ cup / 100g cracked freekeh",
            "8–10 medium Romano peppers or roasting pimentos (1 lb 7 oz / 650g)",
            "16 oz / 450g passata",
            "1¼ cups / 300ml water",
            "¼ cup / 60ml olive oil, plus more for drizzling",
            "3 tbsp pomegranate molasses",
            "2 garlic cloves, crushed to a paste",
            "1¼ tsp dried mint",
            "salt and black pepper",
            "½ a small onion, finely chopped (½ cup / 70g)",
            "¾ cup / 15g fresh parsley, finely chopped, plus more to finish",
            "⅓ cup / 7g fresh mint leaves, thinly shredded, plus more to finish",
            "1 oz / 30g kale leaves, finely chopped",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "1¼ tsp ground cumin",
            "1 tsp ground coriander",
            "heaping ¼ tsp ground cinnamon",
            "heaping ¼ tsp ground allspice",
            "1½ tbsp lemon juice"
        ]
    },
    "TOMATO KUBBEH NEYEH": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 199,
        "recipe": "Tomato kubbeh neyeh",
        "translation": "Abu Amneh",
        "yield": "Serves 4",
        "ingredients": [
            "1 cup / 185g fine bulgur wheat",
            "½ a small onion, finely chopped (⅓ cup / 60g)",
            "1 tbsp red pepper paste (page 29)",
            "¾ cup / 15g fresh mint leaves",
            "½ tsp dried oregano",
            "2½ tsp baharat (page 39)",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "6 large very ripe tomatoes, 4 cut into quarters and the other 2 finely diced",
            "1 tbsp tomato paste",
            "salt",
            "olive oil",
            "crisp lettuce/cabbage leaves",
            "fresh mint leaves",
            "thinly sliced radishes",
            "chopped onions"
        ]
    },
    "GRILLED VEGETABLE SANDWICHES": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 202,
        "recipe": "Grilled vegetable sandwiches",
        "translation": "Makali",
        "yield": "Serves 4",
        "ingredients": [
            "1 small cauliflower, cut into roughly 1½-inch / 4cm florets (12 oz / 350g)",
            "1 small eggplant, sliced into ½-inch / 1½cm rounds (9 oz / 250g)",
            "5 tbsp / 70ml olive oil",
            "1 red onion, cut into ½-inch / 1cm thick slices (1¼ cups / 150g)",
            "salt and black pepper",
            "1 medium zucchini, cut on the diagonal into ½-inch / 1cm thick slices (7 oz / 190g)",
            "2 garlic cloves, crushed to a paste",
            "1 lemon, squeezed to get 1 tbsp juice",
            "½ cup / 10g fresh parsley leaves, roughly chopped",
            "¼ cup / 5g fresh mint leaves, finely shredded",
            "4 pita breads",
            "9 oz / 250g halloumi cheese, cut into ½-inch / 1cm-thick rectangular pieces, 2 x 3 inches / 5 x 7cm",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "tahini sauce (page 32)",
            "1 lemon, cut into wedges"
        ]
    },
    "LENTIL FATTEH": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 206,
        "recipe": "Lentil fatteh",
        "translation": "Fattet Adas",
        "yield": "Serves 4 for light lunch or supper",
        "ingredients": [
            "¾ cup plus 2 tbsp / 180g split red lentils, rinsed and drained",
            "4½ cups / 1100ml water",
            "1 small onion, finely chopped (½ cup / 80g)",
            "1½ tsp ground cumin",
            "½ tsp ground turmeric",
            "heaping ¼ tsp ground allspice",
            "heaping ¼ tsp ground cinnamon",
            "salt and black pepper",
            "2 tbsp olive oil, plus more for drizzling",
            "green lemon sauce (page 28)",
            "2 naan bread, cut into ¾-inch / 2cm pieces (9 oz / 250g)",
            "¼ cup / 40g pistachios",
            "2 tbsp roughly chopped fresh parsley"
        ]
    },
    "MAFTOUL WITH TOMATO, OKRA &YOGURT": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 208,
        "recipe": "Maftoul with tomato, okra &yogurt",
        "translation": "Maftoul bil Banadoura ma’ Bamia",
        "yield": "Serves 4",
        "ingredients": [
            "6 tbsp / 90ml olive oil",
            "1 large onion, peeled and finely sliced (1½ cups / 180g)",
            "5 garlic cloves, peeled and crushed to a paste",
            "¾ tsp ground allspice",
            "1 tsp cumin seeds",
            "½ tsp ground cinnamon",
            "14 oz / 400g cherry tomatoes",
            "1 tbsp tomato paste",
            "1⅔ cups / 400ml water",
            "salt and black pepper",
            "9 oz / 250g maftoul, fregola or pearl couscous",
            "1 lb 2 oz / 500g fresh or frozen okra",
            "Greek yogurt",
            "¼ cup / 5g fresh mint leaves",
            "1 tbsp sumac"
        ]
    },
    "SWEET POTATO KUBBEH WITH CHILE SALSA": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 212,
        "recipe": "Sweet potato kubbeh with chile salsa",
        "translation": "Kubbet Batata Helweh",
        "yield": "Makes 24 pieces, to serve 12 as a snack or 8 as a main",
        "ingredients": [
            "3–4 sweet potatoes (1 lb 9 oz / 700g)",
            "1⅓ cups / 250g coarse bulgur wheat",
            "1⅔ cups / 400ml boiling water",
            "1 onion, finely chopped (1 cup / 150g)",
            "1½ tsp Aleppo chile flakes (or regular chile flakes)",
            "1 tbsp ground cumin",
            "2 tsp ground coriander",
            "2 garlic cloves, crushed to a paste",
            "½ tsp dried oregano",
            "1 cup / 20g fresh parsley, finely chopped",
            "½ cup / 10g fresh dill, finely chopped",
            "3 tbsp olive oil",
            "2 tbsp cornstarch",
            "salt",
            "about 2 cups / 500ml sunflower oil, for frying",
            "2½ tbsp olive oil",
            "3 onions, halved and finely sliced (3½ cups / 450g)",
            "4½ tbsp sumac (1½ oz / 40g)",
            "3 tbsp lemon juice",
            "2 cups / 40g fresh parsley, including stalks, roughly chopped",
            "2 cups / 40g fresh cilantro, including stalks, roughly chopped",
            "1 small green chile, half the seeds removed, roughly chopped",
            "7 tbsp / 110ml olive oil",
            "2 tbsp lemon juice",
            "½ tsp granulated sugar",
            "¼ cup / 60ml water"
        ]
    },
    "BULGURKUBBEH": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 216,
        "recipe": "Bulgurkubbeh",
        "translation": "Kubbet Hileh",
        "yield": "Serves 4",
        "ingredients": [
            "1 cup / 200g fine bulgur wheat",
            "2 tbsp olive oil",
            "1½ tsp ground cumin",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "salt",
            "1½ tbsp red pepper paste (page 29)",
            "1½ cups / 350ml boiling water",
            "½ cup / 2⅓ oz / 65g all-purpose flour",
            "1 garlic clove, crushed to a paste",
            "1 large onion (9 oz / 250g), finely chopped",
            "¼ cup / 60ml olive oil",
            "1 tbsp red pepper paste (page 29)",
            "2 tbsp lemon juice",
            "1 tsp ground cumin",
            "3 tbsp / 65g pomegranate molasses",
            "1 tbsp honey",
            "⅓ cup / 80ml water",
            "½ cup / 10g fresh parsley leaves",
            "¼ cup / 5g fresh mint leaves",
            "1 red chile, finely sliced",
            "⅓ cup / 35g walnuts (optional)",
            "tahini sauce (page 32)"
        ]
    },
    "ASPARAGUS, LEEK & HAZELNUTGALETTE": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 218,
        "recipe": "Asparagus, leek & hazelnutgalette",
        "translation": "Fattiret Halyoun",
        "yield": "Serves 6",
        "ingredients": [
            "2 cups / 9 oz / 240g all-purpose flour",
            "salt and black pepper",
            "10 tbsp / 130g unsalted butter, chilled and cut into ½-inch / 1cm cubes",
            "⅓ cup / 90g Greek yogurt",
            "2 tsp apple cider vinegar",
            "1½ tbsp ice water",
            "¼ cup / 60ml olive oil",
            "2 leeks, white and light green parts only, trimmed and sliced into ½-inch / 1cm slices (7 oz / 200g)",
            "6 oz / 180g soft goat cheese (heaping 1 cup crumbled)",
            "3 oz / 80g cheddar cheese, grated (¾ cup / 90g)",
            "2 garlic cloves, crushed to a paste",
            "1½ tsp lemon zest",
            "1½ tbsp fresh za’atar or oregano leaves, finely chopped",
            "9 oz / 250g asparagus, woody ends trimmed",
            "2 tbsp za’atar",
            "1 egg yolk, beaten with 1 tbsp water, to glaze",
            "3 tbsp / 25g hazelnuts, lightly toasted and roughly chopped"
        ]
    },
    "COUSCOUS FRITTERS WITH PRESERVED LEMON YOGURT": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 223,
        "recipe": "Couscous fritters with preserved lemon yogurt",
        "translation": "Aqras Kosukson",
        "yield": "Serves 4",
        "ingredients": [
            "2 tbsp olive oil",
            "1 medium onion, finely chopped (1¼ cups / 160g)",
            "1 tbsp tomato paste",
            "1 tbsp red pepper paste (page 29)",
            "1 red bell pepper, finely chopped (7 oz / 200g)",
            "4 very ripe tomatoes, cut into ¼-inch / ½cm dice (12 oz / 350g)",
            "3 medium carrots, peeled and coarsely grated (1⅔ cups / 185g)",
            "5¼ oz / 150g couscous",
            "1 cup / 220ml boiling vegetable stock",
            "1 egg",
            "¼ cup / 34g cornstarch",
            "1 tbsp lemon zest",
            "¼ cup / 60ml sunflower oil, for frying",
            "½ cup / 150g Greek yogurt",
            "1 tbsp preserved lemon, finely chopped",
            "1 tbsp capers, finely chopped",
            "1 tbsp fresh dill, finely chopped",
            "1 tsp fresh mint leaves, finely shredded",
            "salt and black pepper"
        ]
    },
    "OUZI PHYLLOPARCELS": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 224,
        "recipe": "Ouzi phylloparcels",
        "translation": "Ouzi",
        "yield": "Serves 6",
        "ingredients": [
            "⅔ cup / 120g Egyptian or other short-grain rice",
            "salt",
            "¾ cup / 160g orzo",
            "5 tbsp / 75ml olive oil",
            "1 medium onion, finely chopped (1¼ cups / 175g)",
            "9 oz / 250g cremini mushrooms, cut into quarters",
            "1¾ tsp ground allspice",
            "¾ tsp ground cinnamon",
            "½ tsp ground cardamom",
            "⅓ tsp ground black pepper",
            "½ tsp ground turmeric",
            "6 large garlic cloves, thinly sliced",
            "12¼ oz / 350g carrots, 3½ oz / 100g coarsely grated (a heaping ¾ cup), the rest cut into ¼-inch / ½cm dice",
            "3 cups / 700ml vegetable stock",
            "1 cup / 150g frozen peas, thawed",
            "¾ cup / 100g golden or regular raisins",
            "¾ cup / 100g toasted nuts and seeds (page 35)",
            "6 tbsp / 85g unsalted butter, melted",
            "15 (12 x 15-inch / 30 x 38cm) sheets of good-quality phyllo pastry, thawed",
            "¼ cup / 5g parsley leaves",
            "1 tbsp olive oil",
            "sumac"
        ]
    },
    "ROASTED EGGPLANT FATTEH": {
        "chapter_idx": 7,
        "category": "Sharing and special occasions",
        "page": 228,
        "recipe": "Roasted eggplant fatteh",
        "translation": "Fattet Makdous",
        "yield": "Serves 4",
        "ingredients": [
            "2 pita breads or 4 large flour tortillas, cut into ¾–1¼ inch / 2–3cm pieces (8½ oz / 240g)",
            "5 tbsp / 70ml olive oil, plus more for drizzling",
            "2 medium eggplants, cut into 1¼-inch / 3cm chunks (1 lb 2 oz / 500g)",
            "2 tsp sumac",
            "½ tsp sweet paprika",
            "salt and black pepper",
            "2 cups / 400g Greek yogurt",
            "3 tbsp tahini paste",
            "1 garlic clove, crushed to a paste",
            "1 green chile, finely chopped",
            "2 tbsp lemon juice",
            "1 medium onion, finely chopped (1¼ cups / 175g)",
            "2 tbsp olive oil",
            "16 oz / 450g passata",
            "1 tbsp pomegranate molasses",
            "¼ cup / 35g whole blanched almonds, toasted",
            "¼ cup / 5g fresh parsley, roughly chopped",
            "1 red chile, finely chopped",
            "3 tbsp / 30g pomegranate seeds (optional)"
        ]
    },
    "JERUSALEM SESAME BREAD NESTS": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 238,
        "recipe": "Jerusalem sesame bread nests",
        "translation": "Ka’ak al Quds ma’ Beyd",
        "yield": "Makes 8",
        "ingredients": [
            "2¼ tsp / 7g fast-acting (instant) dried yeast",
            "1½ tbsp granulated sugar",
            "1¼ cups / 300ml lukewarm water",
            "4 cups / 1 lb 2 oz / 500g all-purpose flour, plus more for dusting",
            "1½ tsp mahlab",
            "1 tsp anise seeds, slightly crushed",
            "salt",
            "3 tbsp sunflower oil, plus more for greasing",
            "9 medium eggs",
            "3 tbsp white sesame seeds",
            "2 tbsp black sesame seeds"
        ]
    },
    "PAN-FRIED TURMERIC BREAD": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 241,
        "recipe": "Pan-fried turmeric bread",
        "translation": "Kubez Kimaaj",
        "yield": "Makes 8",
        "ingredients": [
            "1½ tsp fast-acting (instant) dried yeast",
            "1 tbsp granulated sugar",
            "¾ cup plus 2 tbsp / 200ml lukewarm water",
            "3 cups / 13 oz / 370g all-purpose flour",
            "heaping ¼ tsp ground turmeric",
            "2 tbsp sunflower oil, plus more for greasing",
            "salt"
        ]
    },
    "FENUGREEK & ONION BUNS": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 242,
        "recipe": "Fenugreek & onion buns",
        "translation": "Aqras Helbeh",
        "yield": "Makes 20",
        "ingredients": [
            "1½ tsp fast-acting (instant) dried yeast",
            "1½ tsp granulated sugar",
            "¾ cup plus 2 tbsp / 200ml lukewarm water",
            "3 cups / 13 oz / 370g all-purpose flour, plus more for dusting",
            "salt and black pepper",
            "3 tbsp sunflower oil",
            "1 tbsp olive oil",
            "3 tbsp olive oil",
            "2 large onions, finely chopped (2⅔ cups / 370g)",
            "3 tbsp / 40g fenugreek seeds, soaked overnight in plenty of water",
            "2 tsp ground cumin",
            "¾ tsp ground turmeric",
            "1 tbsp dried mint",
            "7 oz / 200g feta cheese, crumbled (1½ cups) (optional)",
            "3 tbsp olive oil",
            "½ cup / 10g fresh parsley, finely chopped",
            "1 large garlic clove, crushed to a paste"
        ]
    },
    "ZA’ATAR & ANISE CRACKERS": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 246,
        "recipe": "Za’atar & anise crackers",
        "translation": "Malatit",
        "yield": "Makes about 50",
        "ingredients": [
            "¼ cup / 30g white sesame seeds",
            "1 tbsp nigella seeds",
            "2 cups / 9 oz / 250g all-purpose flour",
            "2 tbsp za’atar",
            "1 tbsp ground anise seed",
            "1 tsp Aleppo chile flakes (or regular chile flakes)",
            "heaping ¼ tsp mahlab",
            "1½ tsp baking powder",
            "1 tbsp granulated sugar",
            "salt",
            "3 tbsp / 45ml olive oil",
            "3 tbsp / 50ml sunflower oil",
            "about 7 tbsp / 100ml lukewarm water"
        ]
    },
    "CHEESE AND JAM PIE": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 250,
        "recipe": "Cheese and jam pie",
        "translation": "Musafan",
        "yield": "Serves 6–8",
        "ingredients": [
            "1½ tsp fast-acting (instant) dried yeast",
            "1½ tsp granulated sugar",
            "¾ cup plus 1 tbsp / 190ml lukewarm water",
            "2½ cups / 11¼ oz / 320g all-purpose flour, plus more for dusting",
            "1 tbsp milk powder (optional)",
            "1 tbsp sweet baharat (page 38)",
            "1 tsp ground turmeric",
            "2 tbsp za’atar",
            "salt",
            "2 tbsp / 30ml olive oil, plus more for greasing",
            "1 egg",
            "2 tbsp milk or water",
            "1 tbsp white sesame seeds",
            "1½ tsp nigella seeds",
            "⅔ cup / 200g strawberry jam, or any flavor of jam you like",
            "6 oz / 170g feta cheese, crumbled (1¼ cups)"
        ]
    },
    "OREGANO & CHEESELOAF": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 252,
        "recipe": "Oregano & cheeseloaf",
        "translation": "Kubez al Jeben w al Za’atar",
        "yield": "Serves 6 generously",
        "ingredients": [
            "2 cups plus 2 tbsp / 9½ oz / 270g all-purpose flour",
            "2 tsp baking powder",
            "½ tsp baking soda",
            "1 tsp mahlab",
            "salt",
            "5½ tsp / 15g sesame seeds",
            "2 tsp nigella seeds",
            "2 medium eggs",
            "1 cup / 260ml milk",
            "¼ cup / 60ml olive oil",
            "1 cup / 30g fresh oregano leaves",
            "3½ oz / 100g feta cheese, roughly crumbled (¾ cup)",
            "1¾ oz / 50g halloumi cheese, roughly chopped (⅓ cup)"
        ]
    },
    "WHOLE-WHEAT BREAD": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 256,
        "recipe": "Whole-wheat bread",
        "translation": "Kubez Asmar",
        "yield": "Makes 8",
        "ingredients": [
            "2½ cups / 8¾ oz / 250g whole-wheat flour",
            "⅔ cup / 2¾ oz / 80g all-purpose flour, plus more for dusting",
            "1 tsp fast-acting (instant) dried yeast",
            "1½ tsp granulated sugar",
            "2 tbsp milk powder, optional",
            "salt",
            "¼ cup / 60ml olive oil, plus more for greasing",
            "⅔ cup / 12g fresh oregano or za’atar leaves (optional)",
            "¾ cup / 180ml lukewarm water"
        ]
    },
    "TOASTED BREAD WITH TOMATO & SOUR GRAPES": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 260,
        "recipe": "Toasted bread with tomato & sour grapes",
        "translation": "Mumalah",
        "yield": "Makes 8",
        "ingredients": [
            "4 stale whole-grain pita breads (8½ oz / 240g)",
            "12 oz / 370g black grapes",
            "¼ cup / 60ml olive oil",
            "salt and black pepper",
            "1 onion, finely chopped (1 cup / 150g)",
            "2 medium ripe tomatoes, finely chopped (8½ oz / 240g)",
            "1 tbsp sumac",
            "2 tbsp apple cider vinegar",
            "½ small red onion, very thinly sliced (⅓ cup / 40g)",
            "½ cup / 10g fresh parsley leaves",
            "1 tsp sumac",
            "1 tbsp olive oil",
            "flaked sea salt"
        ]
    },
    "EGG, ONION & FETA OPEN PIE": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 261,
        "recipe": "Egg, onion & feta open pie",
        "translation": "Aqras Beyd",
        "yield": "Serves 4",
        "ingredients": [
            "1 tsp fast-acting (instant) dried yeast",
            "1½ tsp granulated sugar",
            "¾ cup plus 2 tbsp / 200ml lukewarm water",
            "3 cups / 13¼ oz / 375g all-purpose flour, plus more for dusting",
            "2½ tbsp milk powder (optional)",
            "1 tbsp olive oil, plus more for greasing",
            "3 tbsp olive oil",
            "3 onions, peeled, halved and finely sliced (3½ cups / 450g)",
            "2 medium zucchini (11¼ oz / 320g), halved lengthwise, seeds scooped out, and cut lengthwise into 8 batons",
            "4 eggs",
            "salt and black pepper",
            "4 green onions, finely sliced (2 oz / 55g)",
            "3½ oz / 100g feta cheese, crumbled into roughly 1-inch / 2½cm chunks (¾ cup)",
            "¼ cup / 5g fresh oregano leaves",
            "1 tbsp za’atar (optional)",
            "3 tbsp olive oil",
            "2 tsp Aleppo chile flakes (or regular chile flakes)"
        ]
    },
    "CHEESE & SUMAC BITES": {
        "chapter_idx": 8,
        "category": "Bread",
        "page": 265,
        "recipe": "Cheese & sumac bites",
        "translation": "Aqras Jeben",
        "yield": "Makes 20",
        "ingredients": [
            "1½ tsp fast-acting (instant) yeast",
            "1½ tsp granulated sugar",
            "¾ cup / 170ml lukewarm water",
            "2½ cups / 11¼ oz / 320g all-purpose flour",
            "salt",
            "6 tbsp / 90ml sunflower oil, plus more for greasing",
            "1 medium egg",
            "1 tbsp milk",
            "1 tbsp nigella seeds",
            "7 oz / 200g feta cheese, crumbled (1½ cups)",
            "½ cup / 10g fresh parsley, finely chopped",
            "3 green onions, finely sliced (3 oz / 80g)",
            "2 tbsp sumac",
            "½ tsp Aleppo chile flakes (or regular chile flakes)",
            "3 tbsp olive oil"
        ]
    },
    "APRICOT, ORANGE & ALMONDCAKE": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 270,
        "recipe": "Apricot, orange & almondcake",
        "translation": "Ka’ket Mishmash w Burtuqal",
        "yield": "Serves 8–10",
        "ingredients": [
            "¾ cup / 5¼ oz / 150g soft dried apricots",
            "2 large oranges, one zested and both juiced (to give 7 tbsp / 100ml orange juice)",
            "2 tbsp orange blossom water",
            "10 tbsp / 150g unsalted butter, at room temperature, plus more for greasing",
            "½ cup plus 3 tbsp / 5 oz / 135g granulated sugar",
            "salt",
            "zest of 1 lemon",
            "½ cup / 150g Greek yogurt",
            "1½ tsp ground cinnamon",
            "3 large eggs, lightly whisked",
            "2 cups / 6⅓ oz / 180g almond flour",
            "½ cup plus 3 tbsp / 3½ oz / 100g polenta (I use instant polenta)",
            "1 tsp baking powder",
            "1 tsp vanilla bean paste",
            "5–6 fresh apricots, cut in half lengthwise (9½ oz / 270g)",
            "1 egg white",
            "¾ cup / 25g sliced almonds",
            "1 tbsp confectioners’ sugar, plus more for dusting",
            "¼ cup apricot jam",
            "2 tbsp water"
        ]
    },
    "SPICED APPLE, WALNUT & LEMON CAKE": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 274,
        "recipe": "Spiced apple, walnut & lemon cake",
        "translation": "Ka’ket Tuffah w Jawz",
        "yield": "Serves 10–12",
        "ingredients": [
            "1¼ cups / 300ml sunflower oil, plus more for greasing",
            "1½ cups plus 2 tbsp / 11¼ oz / 320g granulated sugar",
            "1 tsp vanilla bean paste",
            "3 large eggs",
            "4 Granny Smith apples, peeled, cored and cut into ¾-inch / 2cm cubes (1 lb / 460g)",
            "2 tbsp lemon juice",
            "3⅔ cups / 16 oz / 450g all-purpose flour, plus more for dusting",
            "1½ tsp ground cinnamon",
            "¾ tsp ground allspice",
            "⅛ tsp ground cloves",
            "1 tsp baking soda",
            "salt",
            "1¼ cups / 150g walnuts, finely chopped",
            "1¼ cups / 5⅔ oz / 160g confectioners’ sugar",
            "2 tbsp lemon juice"
        ]
    },
    "PAN-BAKED TAHINI, HALVA & COFFEE BROWNIE": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 277,
        "recipe": "Pan-baked tahini, halva & coffee brownie",
        "translation": "Qahwa w Halaweh Brownie",
        "yield": "Serves 6",
        "ingredients": [
            "Rounded ½ cup / 150g tahini paste",
            "½ cup / 120ml lukewarm water",
            "Heaping ½ cup / 3¾ oz / 110g granulated sugar",
            "2 large eggs",
            "¼ cup / 20g unsweetened cocoa powder",
            "1 tbsp instant espresso coffee",
            "¼ cup / 1 oz / 30g all-purpose flour",
            "½ tsp ground cardamom",
            "⅛ tsp ground cloves",
            "½ tsp baking powder",
            "salt",
            "1½ oz / 40g dark chocolate chips or chocolate roughly chopped into ¼-inch / ½cm pieces (70% cocoa solids) (⅓ cup chopped)",
            "1½ tbsp sesame seeds",
            "1½ oz / 40g dark chocolate chips or chocolate roughly chopped into ¼-inch / ½cm pieces (70% cocoa solids) (⅓ cup chopped)",
            "⅓ cup / 70g plain or vanilla halva, broken into chunks",
            "vanilla ice cream"
        ]
    },
    "CHOCOLATE DATEBARS": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 278,
        "recipe": "Chocolate datebars",
        "translation": "Ma’amoul bil Shukulata",
        "yield": "Makes 24",
        "ingredients": [
            "2½ cups / 250g walnuts",
            "¼ cup / 60g date paste (or 2¼ oz / 60g pitted medjool dates, finely chopped, plus 1 tbsp sunflower oil)",
            "5 oz / 140g vegan chocolate digestive biscuits, broken into fine crumbs (about 9 biscuits)",
            "packed ½ cup / 100g dark muscovado sugar",
            "¾ tsp ground cardamom",
            "1 tsp ground cinnamon",
            "¾ tsp ground anise seed",
            "½ tsp mahlab",
            "salt",
            "2 tbsp runny honey or agave syrup",
            "2 tbsp rose water",
            "7 oz / 200g vegan dark chocolate (70% cocoa solids), broken into roughly ½-inch / 1cm pieces",
            "¼ oz / 5g freeze-dried raspberries",
            "2 tbsp pistachios, finely crushed"
        ]
    },
    "DATE & NIGELLA SEED ROLLS": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 280,
        "recipe": "Date & nigella seed rolls",
        "translation": "Makrouta",
        "yield": "Makes about 35",
        "ingredients": [
            "¾ cup / 3½ oz / 100g all-purpose flour, plus a little more for dusting",
            "⅓ cup / 1¾ oz / 50g fine semolina",
            "heaping ¼ tsp baking powder",
            "⅛ tsp baking soda",
            "1½ tbsp confectioners’ sugar",
            "½ tsp ground anise seeds",
            "heaping ¼ tsp ground fennel seeds",
            "salt",
            "4 tsp sesame seeds",
            "1½ tsp nigella seeds",
            "zest of ½ a lemon",
            "½ tsp vanilla bean paste",
            "4 tbsp / 60g butter, melted",
            "1 tbsp sunflower oil",
            "2 tbsp / 30ml lukewarm water",
            "confectioners’ sugar, for dusting (optional)",
            "¾ cup / 7 oz / 200g date paste",
            "1 tbsp unsalted butter, at room temperature",
            "½ tbsp sunflower oil"
        ]
    },
    "ANISE & SESAME RUSKS": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 283,
        "recipe": "Anise & sesame rusks",
        "translation": "Arshaleh",
        "yield": "Makes 30",
        "ingredients": [
            "2 cups plus 3 tbsp / 9½ oz / 270g all-purpose flour",
            "1 cup plus 2 tbsp / 8 oz / 220g granulated sugar",
            "2 tbsp finely ground anise seed",
            "2 tsp anise seeds",
            "1 tsp baking powder",
            "heaping ¼ tsp baking soda",
            "3 large eggs",
            "1 tsp vanilla bean paste",
            "7 tbsp / 100ml olive oil",
            "7 tbsp / 100ml sunflower oil",
            "2 tbsp white sesame seeds"
        ]
    },
    "LEMON & PISTACHIO COOKIES": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 286,
        "recipe": "Lemon & pistachio cookies",
        "translation": "Ma’akaroon",
        "yield": "Makes 15",
        "ingredients": [
            "1 cup / 125g pistachios, finely ground",
            "1¼ cups / 125g almond flour",
            "½ cup / 100g granulated sugar",
            "½ tsp mastic, ground",
            "heaping ¼ tsp baking powder",
            "salt",
            "2 tsp finely chopped preserved lemon",
            "1 tsp lemon zest",
            "1 tsp vanilla bean paste",
            "1 tbsp runny honey",
            "1 egg, lightly whisked",
            "1 tbsp unsalted butter, at room temperature",
            "2–3 tbsp confectioners’ sugar, sifted"
        ]
    },
    "TAHINI RICE PUDDING WITH GRAPE COMPOTE": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 289,
        "recipe": "Tahini rice pudding with grape compote",
        "translation": "Helou al Ruz ma’ Antebikh",
        "yield": "Serves 6",
        "ingredients": [
            "¾ cup plus 2 tbsp / 175g Egyptian, risotto or other short-grain rice",
            "1 quart / 1 liter water",
            "salt",
            "heaping ¼ tsp ground turmeric",
            "packed ⅓ cup / 80g light brown sugar",
            "⅓ cup / 90g tahini paste",
            "2 tsp rose water",
            "1 lb 2 oz / 500g black or red seedless grapes",
            "heaping ¼ tsp ground anise seeds",
            "2 tbsp olive oil",
            "1 tbsp butter",
            "2 tbsp toasted pine nuts"
        ]
    },
    "MANGO & SALTED SEEDSPARFAIT": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 290,
        "recipe": "Mango & salted seedsparfait",
        "translation": "Helou al Manga",
        "yield": "Serves 6",
        "ingredients": [
            "2 large or 4 small very ripe mangoes",
            "2 tbsp / 25g granulated sugar",
            "zest and juice of 2 limes",
            "1¾ cups / 450ml heavy cream",
            "1 tsp vanilla bean paste",
            "½ cup / 60g panko breadcrumbs",
            "6 tbsp / 60g sunflower seeds, roughly chopped",
            "4 tbsp / 50g unsalted butter, melted",
            "1 tsp vanilla bean paste",
            "½ tsp ground cinnamon",
            "salt"
        ]
    },
    "CARAWAY & NUT PUDDING": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 294,
        "recipe": "Caraway & nut pudding",
        "translation": "Karawiyah",
        "yield": "Serves 6",
        "ingredients": [
            "1 quart / 1 liter dairy-free milk or water",
            "1½ oz / 45g cornstarch",
            "1 tsp vanilla bean paste",
            "1 tbsp ground caraway seeds",
            "2 tsp ground anise seeds",
            "heaping ¼ tsp ground cinnamon, plus more for sprinkling",
            "⅛ tsp ground cloves",
            "7 tbsp / 100ml agave syrup",
            "¼ cup / 40g walnuts, toasted (seepage 35for how best to do this) and lightly crushed",
            "¼ cup / 25g sliced almonds, toasted",
            "3 tbsp / 30g pistachios, toasted and roughly chopped",
            "¼ cup / 40g golden or regular raisins"
        ]
    },
    "SUMAC ROAST PLUMS WITH CARDAMOM CREAM & PISTACHIO": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 295,
        "recipe": "Sumac roast plums with cardamom cream & pistachio",
        "translation": "Barquq bil Sumac w al Creama",
        "yield": "Serves 4",
        "ingredients": [
            "8 plums (13 oz / 366g)",
            "3 cardamom pods",
            "1 tsp sumac",
            "3 tbsp runny honey",
            "zest of ½ orange",
            "1 tsp lemon juice",
            "1 tbsp water",
            "1¼ cups / 300ml heavy cream",
            "3 tsp honey",
            "heaping ¼ tsp ground cardamom",
            "¼ cup / 45g granulated sugar",
            "heaping ¼ tsp ground cinnamon",
            "3 tbsp water",
            "salt",
            "7 tbsp / 70g pistachios"
        ]
    },
    "LABNEH & POMEGRANATE ICE CREAM": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 298,
        "recipe": "Labneh & pomegranate ice cream",
        "translation": "Bouza bil Labneh w al Rumman",
        "yield": "Serves 6–8",
        "ingredients": [
            "seeds from 1–2 pomegranates (10½ oz / 300g), plus more for garnish",
            "7 tbsp / 120g labneh (page 23)",
            "14 oz / 385g condensed milk",
            "zest and juice of 2 limes (¼ cup / 60ml juice)",
            "2 tbsp rose water",
            "salt",
            "1¼ cups / 300ml heavy cream",
            "2 tbsp confectioners’ sugar",
            "extra-virgin olive oil, for drizzling"
        ]
    },
    "COCONUT, ROSE & CHOCOLATE TRUFFLES": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 301,
        "recipe": "Coconut, rose & chocolate truffles",
        "translation": "Jawz al Hind bil Shukulata",
        "yield": "Makes 25",
        "ingredients": [
            "2¾ cups / 240g fine desiccated coconut",
            "¾ cup / 180ml vegan (or dairy) condensed milk",
            "1 tsp coconut oil",
            "1 tsp vanilla bean paste",
            "salt",
            "9 oz / 260g dark cooking chocolate (75% cocoa solids), roughly chopped",
            "flaked sea salt",
            "dried rose petals",
            "ground pistachios (optional)"
        ]
    },
    "ASHTAH KNAFEH PIE": {
        "chapter_idx": 9,
        "category": "Sweets",
        "page": 302,
        "recipe": "Ashtah knafeh pie",
        "translation": "Knafeh bil Ashtah",
        "yield": "Serves 8–10",
        "ingredients": [
            "2 cups / 500ml whole milk",
            "1 cup / 250ml heavy cream",
            "2 tbsp granulated sugar",
            "⅓ cup / 45g cornstarch",
            "½ tsp mastic",
            "1 tbsp orange blossom water",
            "14 oz / 400g fresh or frozen knafeh (kataifi) pastry (available in most Middle Eastern and Turkish shops), thawed if frozen",
            "¾ cup plus 2 tbsp / 200g unsalted butter, melted",
            "½ cup / 70g pistachios, finely chopped",
            "1½ cups / 300g granulated sugar",
            "¾ cup plus 2 tbsp / 200ml water",
            "2 tablespoons lemon juice",
            "1½ tablespoons orange blossom water"
        ]
    }
}