const CUISINES = [
    "Thanksgiving",
    "Italian",
    "Vietnamese",
    "Abruzzese and Molisan",
    "Acehnese",
    "Afghan",
    "African",
    "Afrikaner",
    "Ainu",
    "Albanian",
    "Algerian",
    "Amazonian",
    "American",
    "American Jewish",
    "American-Chinese",
    "Americas",
    "Ancient Israelite",
    "Ancient Maya",
    "Andalusian",
    "Andhra",
    "Andorran",
    "Anglo-Indian",
    "Angolan",
    "Anguillan",
    "Anhui",
    "Antigua and Barbuda",
    "Arab",
    "Aragonese",
    "Arbëreshë",
    "Arequipan",
    "Argentine",
    "Armenian",
    "Aromanian",
    "Aruban",
    "Ashkenazi Jewish",
    "Asia Minor Greek",
    "Asian",
    "Assamese",
    "Assyrian",
    "Asturian",
    "Asunción",
    "Atlanta",
    "Australasian",
    "Australian",
    "Australian-Chinese",
    "Austrian",
    "Awadhi",
    "Azerbaijani",
    "Aztec",
    "Baden",
    "Bahamian",
    "Bahraini",
    "Balearic",
    "Balinese",
    "Balkan",
    "Balochi",
    "Baltic",
    "Baltimore",
    "Bangladeshi",
    "Banjar",
    "Barbadian",
    "Bashkir",
    "Basilicatan (Lucanian)",
    "Basque",
    "Batak",
    "Bavarian",
    "Beijing",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Bengali",
    "Benin",
    "Berber",
    "Bermudian",
    "Betawi",
    "Bhojpuri",
    "Bhutanese",
    "Bihari",
    "Bolivian",
    "Bosnian",
    "Botswana",
    "Bougainville",
    "Brandenburg",
    "Brazilian",
    "British",
    "British Isles",
    "British Virgin Islands",
    "British-Chinese",
    "Bruneian",
    "Bukharan Jewish",
    "Bulgarian",
    "Burkinabé",
    "Burmese",
    "Burmese-Chinese",
    "Burundian",
    "Buryat",
    "Bush tucker",
    "Cajun",
    "Calabrian",
    "Cali-Mex",
    "California",
    "Cambodian",
    "Cambodian-Chinese",
    "Cameroonian",
    "Canadian",
    "Canadian-Chinese",
    "Canarian",
    "Cantabrian",
    "Cantonese",
    "Cape Verdean",
    "Caribbean",
    "Caribbean-Chinese",
    "Carmarthenshire",
    "Caspian",
    "Castilian-Leonese",
    "Castilian-Manchego",
    "Catalan",
    "Caucasian",
    "Cayman Islands",
    "Centrafrican",
    "Central African",
    "Central American",
    "Central Asian",
    "Central European",
    "Central-Chinese",
    "Ceredigion",
    "Chadian",
    "Cham",
    "Channel Islands",
    "Chaoshan (Teochew)",
    "Chechen",
    "Chettinad",
    "Chiapas",
    "Chicago",
    "Chilean",
    "Chinese",
    "Chinese American",
    "Chinese Buddhist",
    "Chinese Islamic",
    "Christmas Island",
    "Chukchi",
    "Circassian",
    "Colombian",
    "Commander Islands",
    "Comorian",
    "Congolese",
    "Cook Islands",
    "Cornish",
    "Corsican",
    "Cossack",
    "Costa Rican",
    "Cretan",
    "Crimean Tatar",
    "Croatian",
    "Cuban",
    "Cuban-Chinese",
    "Curaçao",
    "Cypriot",
    "Czech",
    "Dagestani",
    "Dakshina Karnataka",
    "Danish",
    "Devonian",
    "Djiboutian",
    "Dominica",
    "Dominican Republic",
    "Dorset",
    "Dutch",
    "East African",
    "East Asian",
    "East Indian",
    "East Timor",
    "Eastern Arabian",
    "Eastern European",
    "Ecuadorian",
    "Egyptian",
    "Emirati",
    "English",
    "Epirotic",
    "Equatorial Guinea",
    "Eritrean",
    "Estonian",
    "Eswatini",
    "Ethiopian",
    "Ethiopian Jewish",
    "Eurasian",
    "European",
    "Extremaduran",
    "Faroese",
    "Fijian",
    "Filipino",
    "Filipino-American",
    "Filipino-Chinese",
    "Finnish",
    "Floribbean",
    "Franconian",
    "French",
    "French Guianan",
    "French-Chinese",
    "Frisian",
    "Fuzhou",
    "Gabonese",
    "Gagauz",
    "Galician",
    "Gambian",
    "Gansu",
    "Georgian",
    "German",
    "German-American",
    "Ghanaian",
    "Gibraltarian",
    "Goan",
    "Goan Catholic",
    "Gower",
    "Greek",
    "Greek-American",
    "Greenlandic",
    "Grenadian",
    "Guamanian",
    "Guangxi",
    "Guatemalan",
    "Guilin",
    "Guinea-Bissauan",
    "Guinean",
    "Guizhou",
    "Gujarati",
    "Guyanese",
    "Hainan",
    "Haipai",
    "Haitian",
    "Hakka",
    "Hamburg",
    "Hangbang",
    "Haute",
    "Hawaiian",
    "Hazara",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hessian",
    "Highland Asian",
    "Hlai",
    "Hmong",
    "Honduran",
    "Hong Kong",
    "Huaiyang",
    "Hubei",
    "Hunan",
    "Hungarian",
    "Hyderabadi",
    "Icelandic",
    "Ilocano",
    "Inca",
    "Indian",
    "Indian-American",
    "Indian-Chinese",
    "Indo",
    "Indo-Caribbean",
    "Indo-Fijian",
    "Indo-South African",
    "Indonesian",
    "Indonesian Arab",
    "Indonesian Indian",
    "Indonesian-Chinese",
    "Inuit",
    "Ionian Islands",
    "Iranian",
    "Iraqi",
    "Irish",
    "Iron Range",
    "Islands of the North Atlantic (IONA)",
    "Israeli",
    "Italian-American",
    "Itameshi",
    "Ivorian",
    "Jain",
    "Jamaican",
    "Japanese",
    "Japanese-American",
    "Japanese-Chinese",
    "Javanese",
    "Jharkhandi",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Jordanian",
    "Kachin",
    "Kaiseki",
    "Kalmyk",
    "Kapampangan",
    "Karakalpak",
    "Karen",
    "Karnataka",
    "Kashmiri",
    "Kazakh",
    "Kentucky",
    "Kenyan",
    "Kerala",
    "Kiribati",
    "Kodava",
    "Komi",
    "Korean",
    "Korean-American",
    "Korean-Chinese",
    "Korean-Mexican",
    "Koryo-saram",
    "Kosovan",
    "Kurdish",
    "Kuwaiti",
    "Kyrgyz",
    "Lahori",
    "Lanna",
    "Lao",
    "Latin American",
    "Latin American-Chinese",
    "Latvian",
    "Lazian or Roman",
    "Lebanese",
    "Leonese",
    "Lesotho",
    "Levantine",
    "Liaoning",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Ligurian",
    "Limburgian",
    "Lithuanian",
    "Livonian",
    "Lombard",
    "Louisiana Creole",
    "Lowcountry",
    "Lower Saxon",
    "Luxembourg",
    "Lyonnaise",
    "Maasai",
    "Macanese",
    "Macedonian",
    "Macedonian  (Greek)",
    "Madrid",
    "Madurese",
    "Maharashtrian",
    "Mainland Southeast Asian",
    "Maithil",
    "Makassar",
    "Malagasy",
    "Malawian",
    "Malay",
    "Malaysian",
    "Malaysian Indian",
    "Malaysian-Chinese",
    "Maldivian",
    "Malian",
    "Maltese",
    "Malvani",
    "Manado",
    "Manchu",
    "Mangalurean",
    "Mangalurean Catholic",
    "Manipuri",
    "Mantuan",
    "Mariana Islands",
    "Maritime Southeast Asian",
    "Maritimes",
    "Marshallese",
    "Martinican",
    "Mauritanian",
    "Mauritian",
    "Mauritian-Chinese",
    "Mecklenburg",
    "Meitei",
    "Melanesian",
    "Mesoamerican",
    "Mexican",
    "Mexican-American",
    "Mexican-Chinese",
    "Mexico City",
    "Miao",
    "Micronesian",
    "Mid-Atlantic United States",
    "Midwestern American",
    "Min",
    "Mindanao",
    "Minnan",
    "Minnesotan",
    "Minorcan",
    "Mizo",
    "Mizrahi Jewish",
    "Moldovan",
    "Mon",
    "Mongolian",
    "Monmouthshire",
    "Montenegrin",
    "Montevideo",
    "Montserrat",
    "Monégasque",
    "Moravian",
    "Mordovian",
    "Moroccan",
    "Mozambican",
    "Mughlai",
    "Muhajir",
    "Muisca",
    "Naga",
    "Nagoya",
    "Namibian",
    "Native American",
    "Nauruan",
    "Navyath Muslim",
    "Neapolitan",
    "Nepalese",
    "New American",
    "New Caledonian",
    "New England",
    "New Jersey",
    "New Mexican",
    "New Nordic",
    "New Orleans",
    "New York City",
    "New Zealand",
    "New Zealand-Chinese",
    "Newari",
    "Nicaraguan",
    "Niger",
    "Nigerian",
    "Ningxia",
    "Niuean",
    "Nordic",
    "North African",
    "North American",
    "North Asian",
    "North Dakota",
    "North East Indian",
    "North Indian",
    "North Korean",
    "North Western-Chinese",
    "Northeastern American",
    "Northeastern-Chinese",
    "Northern European",
    "Northern Irish",
    "Northern-Chinese",
    "Norwegian",
    "Nouvelle",
    "Oaxacan",
    "Occitan",
    "Oceanic",
    "Odesite",
    "Odia",
    "Okinawan",
    "Omaha",
    "Omani",
    "Oriya",
    "Ossetian",
    "Other Indian",
    "Ou",
    "Overseas-Chinese",
    "Pacific Northwest",
    "Padang",
    "Pakistani",
    "Pakistani-Chinese",
    "Palatine",
    "Palauan",
    "Palembang",
    "Palestinian",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Parsi",
    "Pascuense (Easter Island)",
    "Pashtun",
    "Pembrokeshire",
    "Pennsylvania Dutch",
    "Peranakan",
    "Peruvian",
    "Peruvian-Chinese",
    "Peruvian-Japanese",
    "Philadelphia",
    "Pitcairn Islands",
    "Pittsburgh",
    "Polish",
    "Polynesian",
    "Pomeranian",
    "Pontic Greek",
    "Portuguese",
    "Puerto Rican",
    "Puerto Rican-Chinese",
    "Pugliese",
    "Punjabi",
    "Putian (Henghwa)",
    "Qatari",
    "Qinghai",
    "Quebec",
    "Rajasthani",
    "Rhenish-Hessian",
    "Rocky Mountain",
    "Romani",
    "Romanian",
    "Russian",
    "Rwandan",
    "Sabahan",
    "Saint Helenian",
    "Saint Lucian",
    "Sakha",
    "Sakhalin Korean",
    "Salvadoran",
    "Sami",
    "Sammarinese",
    "Samoan",
    "Santomean",
    "Saraiki",
    "Sarawakian",
    "Sardinian",
    "Saudi Arabian",
    "Saxon",
    "Schleswig-Holstein",
    "Scottish",
    "Senegalese",
    "Sephardic Jewish",
    "Serbian",
    "Seychellois",
    "Shaanxi",
    "Shan",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Shippoku",
    "Sichuan",
    "Sicilian",
    "Sierra Leone",
    "Sikkimese",
    "Silesian",
    "Sindhi",
    "Singaporean",
    "Singaporean-Chinese",
    "Slovak",
    "Slovenian",
    "Solomon Islands",
    "Somali",
    "Soul food",
    "South African",
    "South American",
    "South Asian",
    "South Eastern European",
    "South Indian",
    "South Korean",
    "South Sudanese",
    "South Western-Chinese",
    "Southern African",
    "Southern American",
    "Southern European",
    "Southern Thai",
    "Southern-Chinese",
    "Southwestern American",
    "Spanish",
    "Sri Lankan",
    "St. Kitts and Nevis",
    "St. Louis",
    "Sudanese",
    "Sundanese",
    "Surinamese",
    "Swabian",
    "Swedish",
    "Swiss",
    "Syrian",
    "Syrian Jewish",
    "Tagalog",
    "Tahitian",
    "Taiwan",
    "Tajik",
    "Tamil",
    "Tanzanian",
    "Tasmanian",
    "Tatar",
    "Telugu",
    "Tex-Mex",
    "Texan",
    "Thai",
    "Thai-American",
    "Thai-Chinese",
    "Thuringian",
    "Tianjin",
    "Tibetan",
    "Tlingit",
    "Togolese",
    "Tongan",
    "Toronto",
    "Transylvanian Saxon",
    "Trinidad and Tobago",
    "Tripuri",
    "Tujia",
    "Tunisian",
    "Turkish",
    "Turkmen",
    "Turks and Caicos",
    "Tuscan",
    "Tuvaluan",
    "Tuvan",
    "US Virgin Islands",
    "Udmurt",
    "Udupi",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uttar Pradesh",
    "Uttara Karnataka",
    "Uyghur",
    "Uzbek",
    "Valencian",
    "Vanuatuan",
    "Venetian",
    "Venezuelan",
    "Veracruz",
    "Viennese",
    "Vietnamese-American",
    "Vietnamese-Chinese",
    "Visayan",
    "Wa",
    "Wallis and Futuna",
    "Welsh",
    "West African",
    "West Asian",
    "West Indian",
    "Western American",
    "Western European",
    "Western Saharan",
    "Wisconsin",
    "Xinjiang (Uyghur)",
    "Xuzhou",
    "Yamal",
    "Yao",
    "Yemeni",
    "Yi",
    "Yoshoku",
    "Yunnan",
    "Yup'ik",
    "Zambian",
    "Zanzibari",
    "Zhejiang",
    "Zhuang",
    "Zimbabwean"
]

const datalist = document.getElementById('cuisines')
if (!datalist) throw new Error("Unable to locate 'cuisines' element.");
datalist.innerHTML = CUISINES.map(fruit =>`<option value="${fruit}"></option>`).join("");